### ISSUE TITLE
Misc qthreads shim improvements

### ISSUE THREAD

**Issue by ronawho** [chapel-lang/chapel#10000]
There's a bunch of improvements/cleanups to the qthreads shim that'd be nice to get around to

 - [x] Cleanup stack limiting code -- #5749 (done as part of #10254)
 - [x] Fix 0x5F yield frequency in `chpl_sync_lock()` (removed in #10133)
 - [x] Cleanup init/exit code and add comments (done in #10223)
 - [x] Resolve sporadic shutdown hang -- #10074 (done in #10078)
 - [x] Join main pthread to fix leak -- #9819 (done in #10086)
 - [x] Resolve parallel I/O performance issue -- #7748 (done in #10133)
 - [x] Switch `syncvar_t` over to `aligned_t`(done in #10078, #10082)
    - `syncvar_t` still suffers from sync var serialization -- #9651
    - `aligned_t` is what our module code calls for native sync vars, so it's more tested

**Comment by bradcray** [comment]
You won the golden ticket!!!
