### ISSUE TITLE
Remove remaining halts from the standard modules

### ISSUE THREAD

**Issue by ronawho** [chapel-lang/chapel#10002]
Removing the remaining uses of `halt()` from the standard modules, either replacing them with error-handling or halt wrappers where appropriate:

 - [x] remove halts from Barriers.chpl -- #9839 (done in #10220)
 - [x] remove halts from List.chpl -- #9838 (done in #10255)
 - [x] remove halts from Time.chpl -- #9836 (done in #10339)
 - [x] remove halts from Types.chpl -- #9837 (done in #9837)
 
 * [x] remove halts from DynamicIters.chpl (done in #10228 and #10399)
 * [x] remove halts from BigInteger (done in #10272)
 * [x] remove halts from Math.chpl (done in #10391)
 * [x] remove halts from IO.chpl (done in #10346)
