### ISSUE TITLE
Buffered atomic followups

### ISSUE THREAD

**Issue by ronawho** [chapel-lang/chapel#10743]
Followups and improvements to the work done in #10702:

Short Term:
 - [x] Add documentation to BufferedAtomic module
 - [x] Commit more tests
 - [x] Don't build up the chained transaction buffer on the fly. Build up separate buffers and when we have to flush either build up the chained transaction or do nb transactions if chained transactions aren't supported.

Medium Term:
 - [ ] Add support for writeBuff()
 - [ ] Further performance tuning
   - [ ] Any speedup from using HT?
   - [ ] Double buffering/buffer pools (early experiments showed no speedup)
   - [ ] Tune buffer size (64 seemed to be the sweet spot, but other optimizations may require retuning this.

Longer Term:
 - [ ] Auto flush buffers
 - [ ] Add a superrelaxed ordering or a super relaxed code block

**Comment by LouisJenkinsCS** [comment]
> Auto flush buffers

Hopefully when this is finished it can be recycled/reused for CAL.

**Comment by ronawho** [comment]
Closing, I think all the work is done and this issue is quite out of date. Buffered atomics were renamed to unordered atomics, there was some performance tuning done, and we fence at task completion.
