### ISSUE TITLE
Support testing of code examples in documentation

### ISSUE THREAD

**Issue by ben-albrecht** [chapel-lang/chapel#11090]
Today, code examples within documentation(aside from primers) are not automatically tested in any way, making them at risk of going stale over time. By adding a mechanism for testing documentation examples nightly, we could safely include more code examples in the documentation.

A few strategies we could consider:

- Use the `.. literalinclude:: example.chpl` directive to include excerpts from Chapel programs in the testing system.
- Modify the existing [sphinx.ext.doctest](http://www.sphinx-doc.org/en/1.6/ext/doctest.html) extension to generate Chapel programs, instead of Python programs.
- Use some kind of home-grown solution that integrates with `chpldoc` and/or `start_test`.

**Comment by mppf** [comment]
> Use some kind of home-grown solution that integrates with chpldoc and/or start_test.

PR #14165 adds something equivalent to the spectests framework to rst docs (which the spec is now). This, or a similar strategy, could be expanded upon to make a user-facing feature for chpldoc. However a user-facing feature would probably better use `mason test` style tests rather than generating `start_test` ones as the spec tests do now.

However we could immediately apply the spectests framework to technotes and any other .rst documentation that we want to test with start_test.

**Comment by ben-albrecht** [comment]
I have been thinking about this recently in response to some feedback about the docs from new team members, and wonder why we can't start using `literalinclude` to have tested code snippets in the docs right now.

For example, the user's guide already does this:

```rst
.. literalinclude:: examples/users-guide/base/inferredIntValues.chpl
  :caption:
  :language: chapel
  :lines: 1-2
```

**Comment by lydia-duncan** [comment]
I think that's a reasonable solution, though I think having a "doc test" notion in chpldoc itself would still benefit users

**Comment by ben-albrecht** [comment]
> I think that's a reasonable solution, though I think having a "doc test" notion in chpldoc itself would still benefit users

Agreed. I hope we are able to prioritize building something better later, but our docs have suffered long enough from this shortcoming. I think it's time we start including more examples.

**Comment by bradcray** [comment]
The literalinclude approach has been more of a headache than a benefit in the user's guide, and one of the thing that I fret about when I think of returning to that project is whether to rewrite all the existing code to avoid using it.  Specifically, because it refers to files that are outside of the docs directory, developers can/have made updates to the test without noticing that they've broken the user's guide.  For example, imagine that you need to work around a deprecation, and in doing so, add new lines of code to the beginning of the file that shift where the excerpt starts.  Nothing will catch this other than a user reading the documentation or me hopefully trying to remember to see whether any users guide tests changed since the last release.

Tooling could potentially help here, but I'm not sure what it would look like; and the primer-style approach (developed since I started the users guide) in which the code is the documentation as well has proven to be much more robust.

**Comment by mppf** [comment]
I think it'd be pretty easy to extend the spectests facility I described in 
https://github.com/chapel-lang/chapel/issues/11090#issuecomment-546029595 (and that is already implemented) to handle module docs comments - or maybe we just run it on the .rst files after they are generated and then maybe it just works? It's not the prettiest but it doesn't have the problems of literal include.

**Comment by ben-albrecht** [comment]
> Specifically, because it refers to files that are outside of the docs directory, developers can/have made updates to the test without noticing that they've broken the user's guide. For example, imagine that you need to work around a deprecation, and in doing so, add new lines of code to the beginning of the file that shift where the excerpt starts. Nothing will catch this other than a user reading the documentation or me hopefully trying to remember to see whether any users guide tests changed since the last release.

One approach is to have a mechanism that extracts the line numbers referenced from docs into tests, so that you could lock in the lines of code to be extracted into docs. If a developer made a change that modified any code snippets from the docs, they'd see a failing test and need to rerun the mechanism to update the test outputs before pushing their changes.

> primer-style approach (developed since I started the users guide) in which the code is the documentation as well has proven to be much more robust.

The chpl2rst script (primer-style approach) assumes all source code is intended to be displayed in docs, so it would require new features and lots of changes in Chapel module source code to go this route.

> I think it'd be pretty easy to extend the spectests facility

I agree this could be a good route forward. Do you know if we have docs on the rst-ified spectest support? I'm curious about its limitations.

**Comment by mppf** [comment]
> > I think it'd be pretty easy to extend the spectests facility
> 
> I agree this could be a good route forward. Do you know if we have docs on the rst-ified spectest support? I'm curious about its limitations.
> 

What we have is [the script here](https://github.com/chapel-lang/chapel/blob/main/doc/util/extract-rst-tests.py). You can find lots of examples in the spec. Here is one:

```
   *Example (fillTuple3.chpl)*.

   The example from the previous section can be rewritten to use a
   queried type for clarity: 

   .. code-block:: chapel

      proc fillTuple(param p: int, x: ?t) {
        var result: p*t;
        for i in result.indices do
          result(i) = x;
        return result;
      }

   

   .. BLOCK-test-chapelpost

      var x = fillTuple(3, 3.14);
      writeln(x);
      writeln(x.type:string);

   

   .. BLOCK-test-chapeloutput

      (3.14, 3.14, 3.14)
      3*real(64)
```

Don't think we have any good docs for it yet though.

**Comment by bradcray** [comment]
I'm adding a `user issue` label here because users were complaining about our documentation not exhibiting some bitrot and not having enough examples (where I believe fear of bitrot has been one reason we haven't introduced more examples).

**Comment by jabraham17** [comment]
As a data point, grepping for `.. code-block:: chapel` in the standard library
- `modules/standard`: 85 occurrences
- `modules/packages`: 94 occurrences
- `modules/dists`: 26 occurrences
- `modules/internal`: 25 occurrences

Not all of these are good candidates for testing (some are more psuedo-code than real Chapel programs), but many could/should be tested

There are also a handful of occurrences that would be good to test of `.. code-block:: chapel` in other places in the docs, notably in many of the technotes.

**Comment by dlongnecke-cray** [comment]
Hi, I've made a list of all the modules that still need to be updated.

(I got this list doing `grep -rnwl '.' -e '.. code-block:: chapel' | sort | uniq`).

I've checked all these modules and I think the vast majority have code blocks that can be updated to point to tested code. There are a few that contain blocks that are more "pseudo-code".

IMO, I think it would be good to figure out how to have all code snippets be testable in some fashion, even if that means it's a bit more of a PITA for maintainers (maybe that means rewriting a couple snippets to use whole statements).

**If you're working on adjusting modules, please feel free to edit this post to add your name next to what you're working on, or tag me in a comment and I'll add you to the list.**

For my part, I am going to try my hand at documenting some of the codes in the distributions first.

---

- [x] ./dists/BlockCycDist.chpl (@dlongnecke-cray) #27429
- [x] ./dists/BlockDist.chpl (@dlongnecke-cray) ^
- [x] ./dists/CyclicDist.chpl (@dlongnecke-cray) ^
- [x] ./dists/DimensionalDist2D.chpl (@dlongnecke-cray) ^
- [x] ./dists/dims/BlockCycDim.chpl (@dlongnecke-cray) ^
- [x] ./dists/dims/BlockDim.chpl (@dlongnecke-cray) ^
- [x] ./dists/dims/ReplicatedDim.chpl (@dlongnecke-cray) ^
- [x] ./dists/HashedDist.chpl (@dlongnecke-cray) ^
- [x] ./dists/PrivateDist.chpl (@dlongnecke-cray) ^
- [x] ./dists/ReplicatedDist.chpl (@dlongnecke-cray) ^
- [x] ./dists/StencilDist.chpl (@dlongnecke-cray) ^
- [x] ./internal/Atomics.chpl (@dlongnecke-cray) #27459
- [x] ./internal/Bytes.chpl (@dlongnecke-cray) ^
- [x] ./internal/ChapelArray.chpl (@dlongnecke-cray) ^
- [x] ./internal/ChapelDomain.chpl (@dlongnecke-cray) ^
- [x] ./internal/ChapelRange.chpl (@dlongnecke-cray) ^
- [x] ./internal/String.chpl (@dlongnecke-cray) ^
- [x] ./layouts/CompressedSparseLayout.chpl (@dlongnecke-cray) ^
- [x] ./layouts/LayoutCS.chpl (@dlongnecke-cray) [This is deprecated]
- [x] ./packages/AllLocalesBarriers.chpl (@dlongnecke-cray) #27473
- [x] ./packages/ArgumentParser.chpl (@dlongnecke-cray) ^
- [ ] ./packages/AtomicObjects.chpl
- [x] ./packages/CopyAggregation.chpl (@dlongnecke-cray) #27473
- [x] ./packages/Crypto.chpl (@dlongnecke-cray) ^
- [x] ./packages/Curl.chpl (@dlongnecke-cray) ^
- [x] ./packages/DistributedBag.chpl (@Guillaume-Helbecque)
- [x] ./packages/DistributedBagDeprecated.chpl [This is deprecated]
- [x] ./packages/DistributedDeque.chpl (@dlongnecke-cray) #27506
- [x] ./packages/DynamicLoading.chpl (@dlongnecke-cray) #27422
- [ ] ./packages/EpochManager.chpl
- [ ] ./packages/HDFS.chpl
- [ ] ./packages/LAPACK.chpl
- [ ] ./packages/LinearAlgebra.chpl
- [ ] ./packages/LockFreeQueue.chpl
- [ ] ./packages/LockFreeStack.chpl
- [ ] ./packages/ParallelIO.chpl
- [ ] ./packages/PrecisionSerializer.chpl
- [x] ./packages/Python.chpl (@jabraham17)
- [ ] ./packages/RecordParser.chpl
- [ ] ./packages/ReplicatedVar.chpl
- [x] ./packages/TOML.chpl (@Guillaume-Helbecque)
- [ ] ./packages/UnitTest.chpl (@jabraham17 )
- [ ] ./packages/UnorderedAtomics.chpl
- [ ] ./packages/UnorderedCopy.chpl
- [ ] ./packages/URL.chpl
- [ ] ./packages/YAML.chpl
- [ ] ./packages/ZMQ.chpl
- [ ] ./standard/AutoGpu.chpl
- [x] ./standard/BigInteger.chpl (@jabraham17)
- [x] ./standard/ChapelIO.chpl (@dlongnecke-cray) #27491
- [x] ./standard/Collectives.chpl (@Guillaume-Helbecque)
- [x] ./standard/CommDiagnostics.chpl (@dlongnecke-cray) #27491
- [x] ./standard/CTypes.chpl (@dlongnecke-cray) ^
- [x] ./standard/Errors.chpl (@dlongnecke-cray) ^
- [x] ./standard/GMP.chpl (@jabraham17) (the only block is just a `use GMP`)
- [ ] ./standard/GPU.chpl
- [x] ./standard/Help.chpl (@Guillaume-Helbecque)
- [x] ./standard/IO.chpl (@Guillaume-Helbecque) https://github.com/chapel-lang/chapel/pull/27456
- [x] ./standard/JSON.chpl (@dlongnecke-cray) #27491
- [x] ./standard/Map.chpl (@dlongnecke-cray) ^
- [x] ./standard/OS.chpl (@Guillaume-Helbecque)
- [x] ./standard/Random.chpl (@dlongnecke-cray) #27491
- [x] ./standard/Regex.chpl (@dlongnecke-cray) ^
- [x] ./standard/Sort.chpl (@jabraham17) (3 blocks remaining, these are not really testable as they as example code/not meant to be actually written by a user)
- [ ] ./standard/Subprocess.chpl (@Guillaume-Helbecque) (1 block declaring extern var)

**Comment by Guillaume-Helbecque** [comment]
Hi @dlongnecke-cray, I'm not able to edit your post myself so I put here my contributions to this issue. In #27426, I fully tested the `Collectives`, `Help`, `OS`, and `TOML` docs. The `LinearAlgebra` doc is also partially tested, as I have no idea how to compile with BLAS/LAPACK support on the test system. I'm also planning to do the `DistributedBag[Deprecated]` docs.

**Comment by lydia-duncan** [comment]
@Guillaume-Helbecque - I'd be okay with not touching "DistributedBagDeprecated".  Given its name, it's probably time we removed it anyways?

**Comment by Guillaume-Helbecque** [comment]
@lydia-duncan: If I remember correctly, `DistributedBagDeprecated` has been deprecated since version 2.0. However, I don't know if you've had any feedback from users about this.

**Comment by mppf** [comment]
>  I don't know if you've had any feedback from users about this

No feedback that I know of about DistributedBagDeprecated.

**Comment by dlongnecke-cray** [comment]
I'm about done with the distributions and am going to work on the builtin types next (`string`, `atomic`, etc) unless someone else beat me to it.

**Comment by vasslitvinov** [comment]
One consideration for the `literalinclude` solution is whether testing code for documentation should go into `test/release/examples/` or somewhere else under `test/release/` .

Code examples in the spec have gone under `test/release/` so that they are included with Chapel releases. I suggest that other `.chpl` files referenced in documentation also go under `test/release/`. Unless we do not consider it important for them to be included in release tarballs.

**Comment by dlongnecke-cray** [comment]
I also think I would prefer it if all the tests went into the same folder. It makes it easier to find them as opposed to having them all spread out all over the place (where you have to abide by the existing `test/...` file structure, which can sometimes make no sense...).

I think the contents of the files will be copied out when the docs are built, so they don't need to be included in the tarball directly.

**Comment by mppf** [comment]
> I think the contents of the files will be copied out when the docs are built, so they don't need to be included in the tarball directly.

AFAIK the tarball does not include built documentation. Am I wrong about that?

**Comment by jabraham17** [comment]
Yes thats a problem with the literal include approach. You can no longer build the docs from a tarball. We need to also include the sources, which implies to me that we need an equivalent of `release/examples` for these docs tests, as Vass suggests.

**Comment by vasslitvinov** [comment]
> We need to also include the sources, which implies to me that we need an equivalent of release/examples for these docs tests, as Vass suggests.

My proposal is `release/docs/` (or singular), by analogy to `release/spec/`.

There is certainly a benefit to having all tests for a given feature be together within our `test/` tree. My argument in favor of gathering all doc code under `test/release`, besides automatic inclusion in the release tarball, is that such code is intended for illustration whereas the other tests are intended to test correctness and/or performance.

**Comment by bradcray** [comment]
> AFAIK the tarball does not include built documentation.

I thought it did…?  At least, the one I have sitting around from Dec 2024 seems to.  Checking the `gen_release` script seems to confirm that:

```
        log("Building the docs...")
…
            make("chapel-py-venv")
            make("docs")
```

**Comment by mppf** [comment]
Alright, I stand corrected. So that asks the question, is it important to be able to build the docs from the tarball? (given that they are already built)

**Comment by lydia-duncan** [comment]
While I think it would be nice to be able to rebuild the docs from the tarball, I wouldn't expect users to need to do so.  If there's something off with the docs, a screenshot of what's wrong will be the easiest way to report the problem to us and that'll best reflect the experience of every user.  I could potentially think of scenarios where they'd want the .rst files to be sufficient, but I'd prefer users in that unique of a situation actually reach out to us via private channels to tell us what works for them rather than trying to guess at every possible unique situation that could occur.  We only have so many development cycles.

I like the idea of keeping tests of features near other tests of the same feature, which is what the current approach accomplishes.  It allowed me to *reuse* a test for a doc example instead of having to make a separate one, which could eventually add up to saving testing time if we are able to do it enough.

**Comment by bradcray** [comment]
I'm definitely more in the camp of putting testable docs into the release for similar reasons as the tests in the spec—to give users of the release a place to grab it from if they want to try it themselves rather than needing to copy-paste.  I could imagine it potentially supporting a story like https://github.com/chapel-lang/chapel/issues/27198 as well by having a script that maybe opens ATO, adding the test to the session (?).  I'm imagining we'd move such tests into test/release rather than duplicating them / making separate ones.

**Comment by vasslitvinov** [comment]
If we really want to co-locate doc tests with other tests of the same feature, we can have the release script scan `test/` looking for `doc-test` directories and copy those into `test/release/`.

I am still skeptical about it. In order to reuse a test, it is sufficient to symlink to the other copy.

**Comment by lydia-duncan** [comment]
I think it'd be reasonable to move things to the release directory and symlink them back to their better sorted original location, but that'd still result in the test running twice in a full paratest, right?

**Comment by dlongnecke-cray** [comment]
Could we have a release tarball script which goes through all `..literalinclude` and copies those files into a generated folder `release/doc-examples` and then overwrites the path in the `..literalinclude`? So this folder would only be generated for the release.

EDIT: Maybe I'm not clear on if/what the problem is, just throwing ideas at the wall 😄.

---

My opinion having worked on this for a bit is that I'd prefer to add tests to a single flat directory e.g., `test/release/doc-examples`, as that would remove the mental overhead of having to figure out where the heck to put the tests for a certain feature. (It hasn't been _too_ bad - honestly the worst was the dissonance of "why is bytes in `test/types` but array isn't in `test/array`".)

I also don't find there to be much overlap between doc examples and our typical correctness tests. While it's important that a doc example is _correct_, an actual correctness test is usually far more verbose and prioritizes redundancy and edge cases over readability.

**Comment by lydia-duncan** [comment]
> Could we have a release tarball script which goes through all `..literalinclude` and copies those files into a generated folder `release/doc-examples` and then overwrites the path in the `..literalinclude`? So this folder would only be generated for the release.

That'd certainly solve the "runs twice" problem.  Albeit, at the cost of having an additional script to maintain, but it's not the worst idea and could hopefully be relatively straight forward to implement.

> My opinion having worked on this for a bit is that I'd prefer to add tests to a single flat directory e.g., `test/release/doc-examples`, as that would remove the mental overhead of having to figure out where the heck to put the tests for a certain feature. (It hasn't been _too_ bad - honestly the worst was the dissonance of "why is bytes in `test/types` but array isn't in `test/array`".)

My worry with doing that is that someone will think "oh, I've tested `test/types/bytes` and it works fine, and merges something that breaks the docs.  But with these actually in the test system, things are strictly better than they were; we'll get a nightly failure message.  So it's still a forward step over where things were before we started this week and that's what really matters.

> I also don't find there to be much overlap between doc examples and our typical correctness tests. While it's important that a doc example is _correct_, an actual correctness test is usually far more verbose and prioritizes redundancy and edge cases over readability.

I disagree with this categorization.  Behavior can change when complexity is added around it.  There's a reason scientific studies try to isolate as many variables as possible - additional factors change behavior in unexpected ways.  Take the code snippets in #24625 - whether a link could be made depended on many factors and examining both the larger and smaller tests gave a fuller examination of what was going on.  Looking at just the larger one wouldn't show the same information as looking at the smaller code, but similarly looking at just the smaller code didn't reveal everything about what was going on.

We as a team trend towards larger, more complicated cases in a single file today _because our compilation is slow_, not because it is strictly better or worse testing practice to do so.  That compilation cost has discouraged us from writing smaller test code, but we should still do so and there is a benefit to it.  Guillaume's PRs to add documentation involved a mix of both putting multiple cases in a single file and putting them in independent ones and in each case, it was appropriate to do so.  There is not one single way to write a correctness test, because correctness tests need to encapsulate both simplicity and the interaction of features.

**Comment by mppf** [comment]
> I think it'd be reasonable to move things to the release directory and symlink them back to their better sorted original location, but that'd still result in the test running twice in a full paratest, right?

Isn't that easy enough to solve with a directory .notest or .skipif? I imagine we would apply that to the version in release/examples? (A .skipif might be interesting because we could create an environment variable to allow users to test these from the tarball with start_test, should they wish to do so; where normally they are skipped & these same tests are run in their usual directories).

**Comment by dlongnecke-cray** [comment]
Still working away at these. I've started on some of the package modules but they are in general a bit crunchier in terms of how many code snippets they contain.

I'll probably flip to going bottom-up through the list and work on some standard modules after the current batch is done.

**Comment by jabraham17** [comment]
I think we are perhaps over thinking this. I don't think its ever been possible to build the docs from a tarball. We just don't support it.

The `docs` target in the Makefile is in `Makefile.devel`, which is intentionally not included in a release tarball. And confirming:
```bash
> mkdir temp && cd temp
> wget .....
> tar xf chapel-2.5.0.tar.gz
> cd chapel-2.5.0
> make docs
gmake: *** No rule to make target 'docs'.  Stop.
```

And even if you try to build the html from the rst, you get an error
```bash
> cd doc
> make html
Confirming that sphinx-build is available...
OK

Collecting syntax from 'rst/language/spec' into 'rst/language/spec/syntax.rst'
gmake: ./util/collect-syntax.py: No such file or directory
gmake: *** [Makefile:88: collect-syntax] Error 127
```

This is also intentional, we have the explicit step in `gen_release` to remove the `doc/util` directory after building the docs for the tarball.

However, note that the built docs do still have `.. literalinclude:: ....` to files that no longer exist, unlike the user guide which has its examples in the `examples` directory. So if this is a concern we should just put a folder under `examples`, which is already symlinked into the test directory and not duplicated in testing. This doesn't address the issue of having tests for packages in multiple places, but thats already true today. Our test system is only mostly organized, to really be sure when editing a package that you properly test it you just need to run `paratest` over everything. So we wouldn't really be losing anything we have today if we did this

**Comment by dlongnecke-cray** [comment]
Claimed a bunch of standard and package modules from the bottom of the list.

**Comment by Guillaume-Helbecque** [comment]
> (I got this list doing `grep -rnwl '.' -e '.. code-block:: chapel' | sort | uniq`).

@dlongnecke-cray: I discovered while browsing the docs that some code blocks are declared using `.. code-block:: chpl`, such as in `AtomicObjects`, and may have been missed in your list.

**Comment by dlongnecke-cray** [comment]
Oh my! Thanks @Guillaume-Helbecque, looks like I have some more work to do 😄.

**Comment by dlongnecke-cray** [comment]
Luckily not too bad. Added 5 more package modules to the list.

**Comment by jabraham17** [comment]
#27421 adds a CI check to prevent new code examples from being added which aren't tested. As of main right now, its currently flagging ~500 code blocks (both chpl and chapel 😄 ), the majority of which are in technotes and the spec. This is taking into account the currently tested code blocks in the spec, so the spec is not as fully tested as we thought (or the script has a bug and is flagging false positives).

A whole bunch of code blocks can/should be allowed by using `.. BLOCK-test-allowCodeBlock`, as they are just showing signatures or other non-testable example code.

**Comment by dlongnecke-cray** [comment]
List of all the technotes that need adjustment:

- [x] ./allocators.rst (@dlongnecke-cray) #27514
- [x] ./attributes.rst (@dlongnecke-cray) #27509
- [ ] ./dsi.rst [I propose we skip this entirely, it's describing an interface with fragments of code.]
- [x] ./errorHandling.rst (@dlongnecke-cray) #27514
- [ ] ./extern.rst
- [x] ./firstClassProcedures.rst (@dlongnecke-cray) #27514
- [x] ./foreach.rst (@dlongnecke-cray) #27514
- [ ] ./forwarding.rst
- [ ] ./gpu.rst
- [ ] ./initTypeAlias.rst
- [ ] ./interfaces.rst
- [ ] ./ioSerializers.rst
- [ ] ./lifetimeChecking.rst
- [x] ./local.rst (@dlongnecke-cray) #27509
- [x] ./main.rst (@dlongnecke-cray) #27509
- [ ] ./manage.rst
- [ ] ./module_include.rst
- [x] ./nilChecking.rst (@dlongnecke-cray) #27509
- [x] ./noinit.rst (@dlongnecke-cray) #27509
- [ ] ./optimization.rst
- [ ] ./partialInstantiations.rst
- [ ] ./protoGenCodeGuide.rst
- [ ] ./reduceIntents.rst
- [ ] ./remote.rst
- [ ] ./sets.rst
- [ ] ./static.rst
- [ ] ./subquery.rst
- [ ] ./throwingInit.rst
