### ISSUE TITLE
Comments referencing closed issues

### ISSUE THREAD

**Issue by ben-albrecht** [chapel-lang/chapel#11215]
The following files contain comments that refer to closed issues. I assume many of them are TODOs to improve an implementation when that issue is closed, but I have not yet verified every single one (this list was generated by a script):

- [x] `modules/internal/ChapelDistribution.chpl` : #5311 (closed)
  - `d09257e7eb4 (Ben Harshbarger 2017-02-05 19:58:01 -0800 333)`
- [x] `modules/internal/ChapelDistribution.chpl` : #5311 (closed)
  - `58c6a645f4c (Ben Harshbarger 2017-03-01 11:21:16 -0800 920)`
- [x] `modules/standard/IO.chpl` : #7960 (closed)
  - updated in #11241
- [x] `modules/packages/LinearAlgebra.chpl` : #9926 (closed)
  - updated in #11236
- [x] `compiler/passes/resolveIntents.cpp` : #5266 (closed)
  - updated in #11246
- [x] `compiler/codegen/codegen.cpp` : #5887 (closed)
  - updated in #11247

See the list including open issues [here](https://gist.github.com/ben-albrecht/b5a31ce2ee56147bc29710c37ff1a8a8).

**Comment by ben-albrecht** [comment]
It looks like some of these are pointing to closed PRs. I'll update the script to filter PRs out, and will update this list.

**Comment by bradcray** [comment]
Can your script do a 'git blame' to determine who inserted the comments so that they can verify that they should be removed?  Or should that burden fall to the person who closed the issue?

**Comment by ben-albrecht** [comment]
> Can your script do a 'git blame' to determine who inserted the comments so that they can verify that they should be removed?

Sure thing - updated above with `git blame` output attached.

> Or should that burden fall to the person who closed the issue?

I'd be comfortable leaving that burden on the author of the original work-around.

**Comment by ben-albrecht** [comment]
FWIW, I intend to add this script to `util/devel` at some point.

**Comment by bradcray** [comment]
Aw man, @ben-albrecht swooped in and stole the fun of clicking a checkbox!  :'o

**Comment by ben-albrecht** [comment]
Pinging @mppf && @benharsh to make them aware that their name appears in the `git blame` output above.

**Comment by benharsh** [comment]
I'll look at the ChapelDistribution comments.

**Comment by benharsh** [comment]
My two items were resolved by #11251

**Comment by ben-albrecht** [comment]
Thanks everybody!
