### ISSUE TITLE
Add `:throws:` tags to documentation functions that throw errors

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#11417]
If the following functions are documented, that documentation will need to be updated to utilize the `:throws:` tag, following the style decided upon in #11374.  Since there are two hundred of them, I didn't take a look at each one just yet to fully eliminate false positives - I did remove mentions that were obviously comments from the grep command, though.

- [x] modules/internal/ChapelBase.chpl:  proc _waitEndCount(e: _EndCount, param countRunningTasks=true) throws {
- [x] modules/internal/ChapelBase.chpl:  proc _waitEndCount(e: _EndCount, param countRunningTasks=true, numTasks) throws {
- [x] modules/internal/ChapelBase.chpl:  proc _waitDynamicEndCount(param countRunningTasks=true) throws {
- [x] modules/internal/ChapelBase.chpl:  proc _do_command_line_cast(type t, x:c_string) throws {
- [x] modules/internal/ChapelError.chpl:  proc chpl_enum_cast_error(casted: string, enumName: string) throws {
- [x] modules/internal/CString.chpl:  inline proc _cast(type t:chpl_anybool, x:c_string) throws
- [x] modules/internal/CString.chpl:  inline proc _cast(type t:integral, x:c_string) throws
- [x] modules/internal/CString.chpl:  inline proc _cast(type t:chpl_anyreal, x:c_string) throws
- [x] modules/internal/CString.chpl:  inline proc _cast(type t:chpl_anyimag, x:c_string) throws
- [x] modules/internal/CString.chpl:  inline proc _cast(type t:chpl_anycomplex, x:c_string) throws
- [x] modules/internal/StringCasts.chpl:  proc _cast(type t:chpl_anybool, x: string) throws {
- [x] modules/internal/StringCasts.chpl:  inline proc _cast(type t:integral, x: string) throws {
- [x] modules/internal/StringCasts.chpl:  inline proc _cast(type t:chpl_anyreal, x: string) throws {
- [x] modules/internal/StringCasts.chpl:  inline proc _cast(type t:chpl_anyimag, x: string) throws {
- [x] modules/internal/StringCasts.chpl:  inline proc _cast(type t:chpl_anycomplex, x: string) throws {
- [x] modules/packages/BLAS.chpl:    throws where (Adom.rank == 2) && (Bdom.rank==2)
- [x] modules/packages/BLAS.chpl:    throws where (Adom.rank == 2) && (Bdom.rank==2)
- [x] modules/packages/BLAS.chpl:            throws where (Adom.rank == 2) && (vDom.rank == 1)
- [x] modules/packages/BLAS.chpl:            throws where (Adom.rank == 2) && (vDom.rank == 1)
- [x] modules/packages/BLAS.chpl:            throws where (Adom.rank == 2) && (vDom.rank == 1)
- [x] modules/packages/BLAS.chpl:            throws where (Adom.rank == 2) && (vDom.rank == 1)
- [x] modules/packages/BLAS.chpl:           throws where (Adom.rank == 2) && (vDom.rank == 1)
- [x] modules/packages/BLAS.chpl:            throws where (Adom.rank == 2) && (vDom.rank == 1)
- [x] modules/packages/BLAS.chpl:            throws where (Adom.rank == 2) && (vDom.rank == 1)
- [x] modules/packages/BLAS.chpl:            throws where (Adom.rank == 2) && (vDom.rank == 1)
- [x] modules/packages/BLAS.chpl:  proc rotmg(ref d1: ?eltType, ref d2: eltType, ref b1: eltType, b2: eltType, P: []eltType) throws {
- [x] modules/packages/BLAS.chpl:  proc rotm(X: [?D]?eltType,  Y: [D]eltType,  P: []eltType, incY: c_int = 1, incX: c_int = 1) throws
- [x] modules/packages/Buffers.chpl:  private proc create_iobuf():bytes throws {
- [x] modules/packages/Buffers.chpl:  proc buffer.flatten(range:buffer_range) throws {
- [x] modules/packages/Buffers.chpl:  proc =(ref ret:buffer, x:buffer) throws {
- [x] modules/packages/Buffers.chpl:  proc buffer.append(b:bytes, skip_bytes:int(64) = 0, len_bytes:int(64) = b.len) throws {
- [x] modules/packages/Buffers.chpl:  proc buffer.append(buf:buffer, part:buffer_range = buf.all()) throws {
- [x] modules/packages/Buffers.chpl:  proc buffer.prepend(b:bytes, skip_bytes:int(64) = 0, len_bytes:int(64) = b.len) throws {
- [x] modules/packages/Buffers.chpl:  proc buffer.copyout(it:buffer_iterator, out value: ?T):buffer_iterator throws where isNumericType(T) {
- [x] modules/packages/Buffers.chpl:  proc buffer.copyout(it:buffer_iterator, out value: string):buffer_iterator throws {
- [x] modules/packages/Buffers.chpl:                     throws where isNumericType(T) {
- [x] modules/packages/Buffers.chpl:  proc buffer.copyin(it:buffer_iterator, value: string):buffer_iterator throws {
- [x] modules/packages/Crypto.chpl:    proc toHex() throws {
- [x] modules/packages/Crypto.chpl:    proc toHexString() throws {
- [x] modules/packages/Crypto.chpl:    proc encrypt(plaintext: CryptoBuffer, key: CryptoBuffer, IV: CryptoBuffer): owned CryptoBuffer throws {
- [x] modules/packages/Crypto.chpl:  proc createRandomBuffer(buffLen: int) throws {
- [x] modules/packages/Crypto.chpl:    proc getRandomBuffer(buffLen: int): owned CryptoBuffer throws {
- [x] modules/packages/Crypto.chpl:    proc rsaDecrypt(key: RSAKey, iv: [] uint(8), ciphertext: [] uint(8), encKeys: [] CryptoBuffer) throws {
- [x] modules/packages/Crypto.chpl:    proc decrypt(envp: Envelope, key: RSAKey): owned CryptoBuffer throws {
- [x] modules/packages/Curl.chpl:proc file.setopt(opt:c_int, arg):bool throws {
- [x] modules/packages/Curl.chpl:proc file.perform():bool throws {
- [x] modules/packages/Curl.chpl:proc slist.append(str:string) throws {
- [x] modules/packages/HDF5.chpl:                              mode: Hdf5OpenMode) throws {
- [x] modules/packages/HDFS.chpl:proc hdfsChapelConnect(path: c_string, port: int): c_void_ptr throws {
- [x] modules/packages/HDFS.chpl:proc hdfsChapelConnect(path: string, port: int): hdfsChapelFileSystem throws {
- [x] modules/packages/HDFS.chpl:proc hdfsChapelFileSystem.hdfsChapelDisconnect() throws {
- [x] modules/packages/HDFS.chpl:    defaultIOStyle()):hdfsChapelFile throws {
- [x] modules/packages/HDFS.chpl:proc hdfsChapelFile.hdfsClose() throws {
- [x] modules/packages/HDFS.chpl:          style:iostyle = defaultIOStyle(), fs:c_void_ptr):file throws {
- [x] modules/packages/HDFS.chpl:    style:iostyle = defaultIOStyle()):file throws {
- [x] modules/packages/HDFS.chpl:proc hdfsChapelFileSystem_local.hdfs_chapel_disconnect() throws {
- [x] modules/packages/HDFS.chpl:proc hdfs_chapel_connect(path:string, port: int): hdfsChapelFileSystem_local throws {
- [x] modules/packages/HDFS.chpl:proc getHosts(f: file) throws {
- [x] modules/packages/LinearAlgebra.chpl:proc svd(A: [?Adom] ?t) throws
- [x] modules/packages/RecordParser.chpl:  proc get() throws {
- [x] modules/packages/RecordParser.chpl:  proc _get_internal(offst: int(64) = 0, len: int(64) = -1) throws {
- [x] modules/packages/TOML.chpl:    proc parseLoop() : unmanaged Toml throws {
- [x] modules/packages/TOML.chpl:    proc parseValue(): unmanaged Toml throws {
- [x] modules/packages/TOML.chpl:    proc this(tbl: string) ref : unmanaged Toml throws {
- [x] modules/packages/TOML.chpl:    proc printValues(f: channel, v: borrowed Toml) throws {
- [x] modules/packages/TOML.chpl:    proc printValuesJSON(f: channel, v: borrowed Toml, in indent=0) throws {
- [x] modules/packages/TOML.chpl:    proc toString(val: borrowed Toml) : string throws {
- [x] modules/packages/TOML.chpl:    proc tomlType: string throws {
- [x] modules/packages/TOML.chpl:  proc top(source) throws {
- [x] modules/packages/TOML.chpl:    proc nextToke() throws {
- [x] modules/packages/ZMQ.chpl:    proc send(data: string, flags: int = 0) throws {
- [x] modules/packages/ZMQ.chpl:    proc send(data: ?T, flags: int = 0) throws where isNumericType(T) {
- [x] modules/packages/ZMQ.chpl:    proc send(data: ?T, flags: int = 0) throws where isEnumType(T) {
- [x] modules/packages/ZMQ.chpl:    proc send(data: ?T, flags: int = 0) throws where (isRecordType(T) &&
- [x] modules/packages/ZMQ.chpl:    proc recv(type T, flags: int = 0) throws where isString(T) {
- [x] modules/packages/ZMQ.chpl:    proc recv(type T, flags: int = 0) throws where isNumericType(T) {
- [x] modules/packages/ZMQ.chpl:    proc recv(type T, flags: int = 0) throws where isEnumType(T) {
- [x] modules/packages/ZMQ.chpl:    proc recv(type T, flags: int = 0) throws where (isRecordType(T) &&
- [x] modules/packages/ZMQ.chpl:    proc throw_socket_error(socket_errno: c_int, err_fn: string) throws {
- [x] modules/standard/DateTime.chpl:  proc daysInMonth(year: int, month: int) throws {
- [x] modules/standard/FileSystem.chpl:proc locale.chdir(name: string) throws {
- [x] modules/standard/FileSystem.chpl:proc chown(name: string, uid: int, gid: int) throws {
- [x] modules/standard/FileSystem.chpl:proc copy(src: string, dest: string, metadata: bool = false) throws {
- [x] modules/standard/FileSystem.chpl:proc copyFile(src: string, dest: string) throws {
- [x] modules/standard/FileSystem.chpl:proc copyMode(src: string, dest: string) throws {
- [x] modules/standard/FileSystem.chpl:proc copyTree(src: string, dest: string, copySymbolically: bool=false) throws {
- [ ] **private** modules/standard/FileSystem.chpl:private proc copyTreeHelper(src: string, dest: string, copySymbolically: bool=false) throws {
- [x] modules/standard/FileSystem.chpl:proc locale.cwd(): string throws {
- [x] modules/standard/FileSystem.chpl:proc exists(name: string): bool throws {
- [x] modules/standard/FileSystem.chpl:proc getGID(name: string): int throws {
- [x] modules/standard/FileSystem.chpl:proc getMode(name: string): int throws {
- [x] modules/standard/FileSystem.chpl:proc getFileSize(name: string): int throws {
- [x] modules/standard/FileSystem.chpl:proc getUID(name: string): int throws {
- [x] modules/standard/FileSystem.chpl:proc isDir(name:string):bool throws {
- [x] modules/standard/FileSystem.chpl:proc isFile(name:string):bool throws {
- [x] modules/standard/FileSystem.chpl:proc isLink(name: string): bool throws {
- [x] modules/standard/FileSystem.chpl:proc isMount(name: string): bool throws {
- [x] modules/standard/FileSystem.chpl:proc mkdir(name: string, mode: int = 0o777, parents: bool=false) throws {
- [x] modules/standard/FileSystem.chpl:proc moveDir(src: string, dest: string) throws {
- [x] modules/standard/FileSystem.chpl:proc rename(oldname: string, newname: string) throws {
- [x] modules/standard/FileSystem.chpl:proc remove(name: string) throws {
- [x] modules/standard/FileSystem.chpl:proc rmTree(root: string) throws {
- [ ] **private** modules/standard/FileSystem.chpl:private proc rmTreeHelper(root: string) throws {
- [x] modules/standard/FileSystem.chpl:proc sameFile(file1: string, file2: string): bool throws {
- [x] modules/standard/FileSystem.chpl:proc sameFile(file1: file, file2: file): bool throws {
- [x] modules/standard/FileSystem.chpl:proc symlink(oldName: string, newName: string) throws {
- [x] modules/standard/IO.chpl:proc stringStyleWithLength(lengthBytes:int) throws {
- [x] modules/standard/IO.chpl:proc file.check() throws {
- [ ] **no doc** modules/standard/IO.chpl:proc file._style:iostyle throws {
- [x] modules/standard/IO.chpl:proc file.close() throws {
- [x] modules/standard/IO.chpl:proc file.fsync() throws {
- [x] modules/standard/IO.chpl:proc file.path : string throws {
- [x] modules/standard/IO.chpl:proc file.length():int(64) throws {
- [x] modules/standard/IO.chpl:proc open(path, mode, hints, style, url): file throws {
- [x] modules/standard/IO.chpl:proc openfd(fd: fd_t, hints:iohints=IOHINT_NONE, style:iostyle = defaultIOStyle()):file throws {
- [x] modules/standard/IO.chpl:proc openfp(fp: _file, hints:iohints=IOHINT_NONE, style:iostyle = defaultIOStyle()):file throws {
- [x] modules/standard/IO.chpl:proc opentmp(hints:iohints=IOHINT_NONE, style:iostyle = defaultIOStyle()):file throws {
- [x] modules/standard/IO.chpl:proc openmem(style:iostyle = defaultIOStyle()):file throws {
- [ ] **no doc** modules/standard/IO.chpl:proc channel._ch_ioerror(error:syserr, msg:string) throws {
- [ ] **no doc** modules/standard/IO.chpl:proc channel._ch_ioerror(errstr:string, msg:string) throws {
- [x] modules/standard/IO.chpl:inline proc channel.lock() throws {
- [x] modules/standard/IO.chpl:proc channel.advance(amount:int(64)) throws {
- [x] modules/standard/IO.chpl:proc channel.advancePastByte(byte:uint(8)) throws {
- [x] modules/standard/IO.chpl:proc openreader(path .... url:string=""): channel(false, kind, locking) throws {
- [x] modules/standard/IO.chpl:proc openwriter(path .... url:string=""): channel(true, kind, locking) throws {
- [x] modules/standard/IO.chpl:proc file.reader(param kind .... style:iostyle = this._style): channel(false, kind, locking) throws {
- [x] modules/standard/IO.chpl:proc file.lines(param locking .... hints:iohints = IOHINT_NONE, in local_style:iostyle = this._style) throws {
- [x] modules/standard/IO.chpl:proc file.writer(param kind .... channel(true,kind,locking) throws {
- [x] modules/standard/IO.chpl:  proc channel.writeBytes(x, len:ssize_t):bool throws {
- [ ] **TODO - merge with the other read()** modules/standard/IO.chpl:inline proc channel.read(ref args ...?k):bool throws {
- [x] modules/standard/IO.chpl:proc channel.read(ref args ...?k, style:iostyle):bool throws {
- [ ] **TODO** modules/standard/IO.chpl:proc channel.readline(arg .... amount = arg.domain.high - start + 1) : bool throws
- [x] modules/standard/IO.chpl:proc channel.readline(ref arg:string):bool throws {
- [x] modules/standard/IO.chpl:proc channel.readstring(ref str_out:string, len:int(64) = -1):bool throws {
- [x] modules/standard/IO.chpl:inline proc channel.readbits(out v:integral, nbits:integral):bool throws {
- [x] modules/standard/IO.chpl:proc channel.writebits(v:integral, nbits:integral):bool throws {
- [ ] **no doc** modules/standard/IO.chpl:proc channel.readln():bool throws {
- [ ] **no doc** modules/standard/IO.chpl:proc channel.readln(ref args ...?k):bool throws {
- [x] modules/standard/IO.chpl:proc channel.readln(ref args ...?k, style:iostyle):bool throws {
- [x] modules/standard/IO.chpl:proc channel.read(type t) throws {
- [x] modules/standard/IO.chpl:proc channel.readln(type t) throws {
- [x] modules/standard/IO.chpl:proc channel.readln(type t ...?numTypes) throws where numTypes > 1 {
- [x] modules/standard/IO.chpl:proc channel.read(type t ...?numTypes) throws where numTypes > 1 {
- [ ] **no doc** modules/standard/IO.chpl:inline proc channel.write(const args ...?k):bool throws {
- [x] modules/standard/IO.chpl:proc channel.write(const args ...?k, style:iostyle):bool throws {
- [ ] **no doc** modules/standard/IO.chpl:proc channel.writeln():bool throws {
- [ ] **no doc** modules/standard/IO.chpl:proc channel.writeln(const args ...?k):bool throws {
- [x] modules/standard/IO.chpl:proc channel.writeln(const args ...?k, style:iostyle):bool throws {
- [x] modules/standard/IO.chpl:proc channel.flush() throws {
- [ ] **no doc** modules/standard/IO.chpl:proc channel.atEOF(): bool throws {
- [x] modules/standard/IO.chpl:proc channel.close() throws {
- [ ] **no doc** modules/standard/IO.chpl:proc channel.readBytes(x, len:ssize_t) throws {
- [ ] **not needed** modules/standard/IO.chpl:  proc read(out arg:ItemType):bool throws {
- [ ] **not needed** modules/standard/IO.chpl:  proc write(arg:ItemType):bool throws {
- [ ] **not needed** modules/standard/IO.chpl:proc read(ref args ...?n):bool throws {
- [ ] **not needed** modules/standard/IO.chpl:proc readln(ref args ...?n):bool throws {
- [ ] **no doc** modules/standard/IO.chpl:proc readln():bool throws {
- [ ] **not needed** modules/standard/IO.chpl:proc readln(type t ...?numTypes) throws {
- [ ] **not needed** modules/standard/IO.chpl:proc read(type t ...?numTypes) throws {
- [x] modules/standard/IO.chpl:proc unlink(path:string) throws {
- [ ] **no doc** modules/standard/IO.chpl:proc file.fstype():int throws {
- [x] modules/standard/IO.chpl:proc file.getchunk(start:int(64) = 0, end:int(64) = max(int(64))):(int(64),int(64)) throws {
- [x] modules/standard/IO.chpl:proc channel.writef(fmtStr: string, const args ...?k): bool throws {
- [ ] **no doc** modules/standard/IO.chpl:proc channel.writef(fmtStr:string): bool throws {
- [x] modules/standard/IO.chpl:proc channel.readf(fmtStr:string, ref args ...?k): bool throws {
- [ ] **no doc** modules/standard/IO.chpl:proc channel.readf(fmtStr:string) throws {
- [ ] **not needed** modules/standard/IO.chpl:proc readf(fmt:string, ref args ...?k):bool throws {
- [ ] **no doc** modules/standard/IO.chpl:proc readf(fmt:string):bool throws {
- [x] modules/standard/IO.chpl:proc channel.skipField() throws {
- [x] modules/standard/IO.chpl:proc string.format(args ...?k): string throws {
- [ ] **private** modules/standard/IO.chpl:private inline proc chpl_do_format(fmt:string, args ...?k): string throws {
- [x] modules/standard/IO.chpl:proc channel.extractMatch(m:reMatch, ref arg) throws {
- [ ] **no doc** modules/standard/IO.chpl:proc channel.search(re:regexp):reMatch throws
- [ ] **TODO** modules/standard/IO.chpl:proc channel.search(re:regexp, ref captures ...?k): reMatch throws
- [ ] **no doc** modules/standard/IO.chpl:proc channel.match(re:regexp):reMatch throws
- [ ] **TODO** also deprecate the error= version: modules/standard/IO.chpl:proc channel.match(re:regexp, ref captures ...?k):reMatch throws
- [x] modules/standard/Path.chpl:proc file.getParentName(): string throws {
- [ ] modules/standard/Path.chpl:proc realPath(name: string): string throws {
- [ ] modules/standard/Path.chpl:proc file.realPath(): string throws {
- [x] modules/standard/Random.chpl:    proc skipToNth(n: integral) throws {
- [x] modules/standard/Random.chpl:    proc getNth(n: integral): eltType throws {
- [x] modules/standard/Random.chpl:      proc skipToNth(n: integral) throws {
- [x] modules/standard/Random.chpl:      proc getNth(n: integral): eltType throws {
- [x] modules/standard/Random.chpl:      proc skipToNth(n: integral) throws {
- [x] modules/standard/Random.chpl:      proc getNth(n: integral): eltType throws {
- [x] modules/standard/Regexp.chpl:proc compile(pattern: string, utf8=true, posix=false, literal=false, nocapture=false, /*i*/ ignorecase=false, /*m*/ multiline=false, /*s*/ dotnl=false, /*U*/ nongreedy=false):regexp throws {
- [ ] modules/standard/Regexp.chpl:inline proc _cast(type t, x: string) throws where t == regexp {
- [x] modules/standard/Spawn.chpl:    proc _throw_on_launch_error() throws {
- [x] modules/standard/Spawn.chpl:    proc stdin throws {
- [x] modules/standard/Spawn.chpl:    proc stdout throws {
- [x] modules/standard/Spawn.chpl:    proc stderr throws {
- [x] modules/standard/Spawn.chpl:             param kind=iokind.dynamic, param locking=true) throws
- [x] modules/standard/Spawn.chpl:                  param kind=iokind.dynamic, param locking=true) throws
- [x] modules/standard/Spawn.chpl:  proc subprocess.poll() throws {
- [x] modules/standard/Spawn.chpl:  proc subprocess.wait(buffer=true) throws {
- [x] modules/standard/Spawn.chpl:  proc subprocess.communicate() throws {
- [ ] modules/standard/Spawn.chpl:  proc subprocess.close() throws {
- [ ] modules/standard/Spawn.chpl:  proc subprocess.send_signal(signal:int) throws {
- [ ] modules/standard/Spawn.chpl:  proc subprocess.kill() throws {
- [ ] modules/standard/Spawn.chpl:  proc subprocess.terminate() throws {
- [x] modules/standard/SysError.chpl:proc ioerror(error:syserr, msg:string, path:string, offset:int(64)) throws
- [x] modules/standard/SysError.chpl:proc ioerror(error:syserr, msg:string, path:string) throws
- [x] modules/standard/SysError.chpl:proc ioerror(error:syserr, msg:string) throws
- [x] modules/standard/SysError.chpl:proc ioerror(errstr:string, msg:string, path:string, offset:int(64)) throws

**Comment by dlongnecke-cray** [comment]
Just a heads up, I'm starting from the top of the list and working my way down to `modules/packages/Buffers.chpl`.

**Comment by vasslitvinov** [comment]
I am working on `modules/standard`

**Comment by dlongnecke-cray** [comment]
I have a PR up for all the throws from list start to ``modules/packages/Buffers.chpl``, #12574. I'll handle the rest of the items in ``modules/packages`` now.

**Comment by lydia-duncan** [comment]
@vasslitvinov - when you get the chance, can you add checkmarks for the ones covered in your PR?

**Comment by vasslitvinov** [comment]
I checkmarked mine, for #12579.
I labeled a few of those that do not need annotation.

Follow-up items:

* A couple of functions, marked with "todo", still need :throws: in their chpldoc.

* Deprecate the `error=` version of `proc channel.match()` and move its chpldoc to the throwing version. Unless there is a reason not to.

* A few channel methods that lock the channel will halt() if the lock() method throws. I.e. they invoke lock() within try!. As an outsider, I do not see why halt and not re-throw. If we stick with this approach, we should at least document it.

* Follow up on the two methods whose chpldoc can be merged with the other ones. Follow up on Michael's comment on these.

* Do we really want `chpldoc` to support both `:throw` and `:throws` - singular and plural?
  Feels unnecessary.

**Comment by lydia-duncan** [comment]
Huh, not sure how I missed this comment.

> A few channel methods that lock the channel will halt() if the lock() method throws. I.e. they invoke lock() within try!. As an outsider, I do not see why halt and not re-throw. If we stick with this approach, we should at least document it.

That seems reasonable to me

> Do we really want chpldoc to support both :throw and :throws - singular and plural?
Feels unnecessary.

We do something similar for `:returns:`, so it is consistent.  I prefer the `:throws:` version and it wasn't hard to support both (and I have a vague memory of Python doing something similar)

**Comment by Aniket21mathur** [comment]
@lydia-duncan all the `proc`s in `ZMQ.chpl` have the `no doc` pragma.

**Comment by lydia-duncan** [comment]
> @lydia-duncan all the procs in ZMQ.chpl have the no doc pragma.

Hmm, that's true, but it looks like they are overloads of another method that is documented.  So I think that documentation should mention that for some potential types of data, the method can throw and the documentation should cover what can be thrown.

**Comment by piyush0411** [comment]
Hi @lydia-duncan Mam
I have started working on this issue and made a pull request #17338 
Kindly have a look and review the changes made.

**Comment by arifthpe** [comment]
Taking the remaining package modules on the list in https://github.com/chapel-lang/chapel/pull/27440
