### ISSUE TITLE
leader/follower improvements

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#11505]
As a Chapel user, I'd like to be able to easily implement leader/follower iterators for my types and combine leader/follower iterators from different types.

This epic tracks leader-follower areas of improvement.

**Comment by mppf** [comment]
@vasslitvinov, @daviditen FYI. I hope we can record thoughts about leader/follower design problems here and link to issues discussing solutions.

**Comment by mppf** [comment]
The [leader/follower paper](http://pgas11.rice.edu/papers/ChamberlainEtAl-Chapel-Iterators-PGAS11.pdf) says this:

>  One ... limitation is related to zippered iteration over multidimensional data structures. Because zippered serial iterationis  implemented  via  methods  on  an  object,  the  multidimensional control  flow  is  pushed  into  the  object’s  single advance method,which  is  then  zippered  with  all  of  the  other  objects’  methods  in a 1D loop. This results in a suboptimal control structure compared to the loop nest a programmer would manually write for a multi dimensional zippered iteration. To that end, we anticipate extending the leader-follower interface to support distinct iterators for each dimension. Multidimensional loop nests would then be generated by zippering each dimension’s iterators separately.

> A  second  concern  relates  to  parallel  loop  startup  overhead.Since each forall loop leader creates parallelism, tasks are created and destroyed for each forall loop. By breaking the leader iterator into two calls—one to create tasks, and the other to assign work to them—the compiler could fuse multiple forall loops, inserting appropriate  synchronization  to  maintain  correct  semantics  while reusing the same tasks.

> In both of these scenarios, there will be a need to share state between the collection of iterators that define the leader and followers. To that end, we anticipate moving to more of an object-based framework for leader-follower iterators in which the various iterators would be defined as methods fulfilling an iterator interface. This would also solve some of the awkwardness of grouping iterators via overloading and the compiler-provided tag argument.

**Comment by bradcray** [comment]
It's not a publicly available document, but for those on the HPE team, `2014-04-21-leader-follower.txt` has notes on this general topic as well.  Let me know if you need a pointer to it.

**Comment by vasslitvinov** [comment]
Other related issues:
* [ ] user-level "iterator record" datatype? #11435 
* [ ] "shape" of an iterator / promoted expr / forall-expr a user-facing feature #10359
* [ ] allow user to declare an iterator's shape #11524
* [ ] leader/follower syntax proposal #13256
* [ ] allow promotion of iterators? #11879
* [ ] serial/parallel iterator forwarding feature #5255
* [ ] myIter().type to be myIter's yield type? #5578

**Comment by lydia-duncan** [comment]
Recording here so things are more "in one place":
- Set zippering issue (https://github.com/chapel-lang/chapel/issues/15824) and an initial attempt at a solution within the confines of leader-follower today (https://github.com/chapel-lang/chapel/pull/26595, would benefit from being able to share information about the iteration space, as mentioned above)
