### ISSUE TITLE
String design questions

### ISSUE THREAD

**Issue by dmk42** [chapel-lang/chapel#11750]
The following are questions to resolve regarding the functionality of strings.

- [x] 1.  Should only one multibyte string representation be supported, or many? #11745
- [x] 1a.  If we support more than one multibyte encoding, should the encoding be determined on a per-program basis or a per-string basis?  N/A -- only one encoding supported

- [x] 2.  Should a string be able to store non-multibyte-character data, e.g. binary data? #11748

- [x] 3.  Should Chapel users be able to request byte or codepoint indexing explicitly? #11749

- [x] 4.  What units of string indexing, iteration, and slicing should be supported? #11849

- [x] 5.  What character classes/properties should be supported? #11850

- [x] 6.  What types should indexing and iteration return? #11061

**Comment by mppf** [comment]
I think #11061 brings up a question (should string `this` return some kind of integer or `string`?) that is just as important to resolve as the above 3 in the near term.

**Comment by dmk42** [comment]
All the issues here have now been addressed.
