### ISSUE TITLE
Performance regressions since 1.18

### ISSUE THREAD

**Issue by ronawho** [chapel-lang/chapel#12418]
Here's all the outstanding performance regressions that I'm aware of since our last release:

Important:
 - [x] tuple to complex regression: https://github.com/chapel-lang/chapel/issues/12347
 - [x] comm count regression for remote record copies: https://github.com/chapel-lang/chapel/issues/11730
 - [x] memory leak regression for several tests: https://github.com/chapel-lang/chapel/issues/12125 / https://github.com/Cray/chapel-private/issues/24

Less important, but would be nice to at least understand: 
 - [x] NPB EP regression: https://github.com/chapel-lang/chapel/issues/12173
 - [x] Compiler performance regression: https://github.com/chapel-lang/chapel/issues/12142
