### ISSUE TITLE
Sparse Arrays/Domains Meta-issue

### ISSUE THREAD

**Issue by e-kayrakli** [chapel-lang/chapel#12674]
This is a metaissue to track sparse array/domain issues.

Functionality
-------------

- [ ] Slicing  (#9813, and many others linked from that)
- [ ] Iterators in subset of dimensions  (#7374)
- [ ] Buffered bulk index addition (#12672)
- [ ] Local index addition  (#12673)
- [ ] Bulk index removal (No issue yet, probably low priority)

Performance
-----------

- [ ] Sparse Array assignment (#9344)

Design Questions
----------------

- [ ] Cross-type assignments for arrays  (#7788)

- [ ] Zippering sparse arrays/domains with other iterables. (#12424, #11504, #9437, and many others. Oldest issues I could see: #6577)

**Comment by e-kayrakli** [comment]
@ben-albrecht suggested creating this issue both to track the issues and help those who are interested in contributing to the sparse domain/array support in Chapel.

Anyone with the right permissions should feel free to modify the contents of the original post.

**Comment by himbhadani** [comment]
Thanks @e-kayrakli Sir,
This meta-issue is surely going to help me a lot.:)

**Comment by bradcray** [comment]
Only loosely related, but I wanted to mention that I'm putting in an effort to look into what it would take to slice dense arrays with sparse domains.

**Comment by e-kayrakli** [comment]
@bradcray -- I am trying to track what happens on github but, if you happen to open an issue capturing what you think about that, IMHO it should be listed in this issue as well. Such support would definitely increase the usability of sparse domains.

Feel free to ping me up if you open an issue and I miss it.

**Comment by bradcray** [comment]
I think you're right that I haven't opened up an issue for this case yet.  I was hoping to just get it done before ever finding the time to open the issue.  :)

**Comment by bradcray** [comment]
(in fact, I just tried it for the first time on the slicing branch I've been developing independently of the sparse domain slicing question, and it seems to work! :) ).

**Comment by e-kayrakli** [comment]
A PR is always better than an issue, I guess :)

**Comment by bradcray** [comment]
The branch is still going well, but I opened issue #12704 all the same.
