### ISSUE TITLE
Non-nilable type checking meta-issue

### ISSUE THREAD

**Issue by vasslitvinov** [chapel-lang/chapel#13598]
This is a summary of nilability / nil checking issues.
Starting point: nilable types #12614

#### Design-ish

* [x] a `const ref` version of owned.borrow() ? #13638
* [ ] behavior of `!` w.r.t. `--fast` and performance impact  #13603
  - aka skip the runtime check for '!' upon --fast?

#### Convenience features
* [ ] nilability ergonomics features #16931
  - [ ] incl. preserve memory management in control-flow declarations #17575
* [ ] Reconcile PRIM_GATHER_TESTS with --no-legacy-nilable-classes #13755
* [ ] Should not need `!` for accessing param fields and similar #13617 (resolved), #14705 (open)

#### Bugs, would-be-nice

* [ ] Misleading error message with an incorrectly-non-nilable value #13629
* [ ] Disappeared "note" in compiler output #13635

#### Resolved issues

* [x] Remove `--legacy-classes` option
* [x] Nil checker catches a valid program #11918
* [x] no tests relying on `--legacy-classes`
* [x] make prototype modules no longer enable implicit `!` #14559
  - generally, prototype modules to not affect nilability
* [x] stop permitting `!` to be applied to types
* [x] replace `new owned (value)` (?) #14300
* [x] subtype relationship between non-nilable and nilable? #14307
* [x] Missing nil checking for the array element type #13602
* [x] Missing nil checking upon ownership transfer #13600
  - depends on expiring values #13704
* [x] Missing nil checking upon initialization #13599
* [x] Misleading error upon returning a nilable #13601
* [x] Can't assign to nilable shared from non-nilable owned #13714
* [x] Enable compile-time nil checking for internal modules #11305
* [x] A nilable generic formal instantiates to a non-nilable type #13615
* [x] Missed forwarding-cycle detection #13631
* [x] Spurious "cannot default-initialize" error #13632
* [x] Different meaning of 'arg: MyClass' upon --legacy-nilable-classes #13720
* [x] Invalid generated C code upon a use of postfix-`?` -- #13759
* [x] Switch to `--no-legacy-classes` by default
* [x] Convert arkouda to `--no-legacy-classes`
* [x] What should `new [flavor] C()?` mean? #13619
* [x] Should the result of `x!` be an alias to `x`? #13621
* [x] owned MyClass? prints out improperly with --no-devel #13431
* [x] Support default intialization + assignment #13618
* [x] Missed nil checker errors #13630
* [x] How to update test/compflags/ferguson/unstable-class.chpl? #13628
* [x] Fix chpl__buildDistType #13634
* [x] Infer non-nil-ness inside a conditional (from #13397) #13639
  - How does this interact with nil checking?
* [x] Won't-fix for now:
  - How to / should we preserve old-style runtime nil checking? #13625

**Comment by bradcray** [comment]
By pinning this issue, my concern is more w.r.t. the tests that are requiring `--legacy-classes` to keep working than anything (and maybe that list should be split off into its own epic / issue as a result).

**Comment by vasslitvinov** [comment]
@bradcray - perhaps unpin this issue now?

**Comment by vasslitvinov** [comment]
This issue has served its purpose. Closing.

The individual issues linked from here are unaffected by closing this issue.
