### ISSUE TITLE
Stabilize the atomic interface

### ISSUE THREAD

**Issue by ronawho** [chapel-lang/chapel#13826]
As part of stabilizing the core language, there are few items we need to change for the atomic API:

 - [x] Decide what to do with `peek()`/`poke()` -- https://github.com/chapel-lang/chapel/issues/13827 (done in https://github.com/chapel-lang/chapel/pull/13888)
 - [x] Replace C memory orders with a Chapel enum -- https://github.com/chapel-lang/chapel/issues/13829 (done in https://github.com/chapel-lang/chapel/pull/13900)
 - [x] Add user-facing fences -- https://github.com/chapel-lang/chapel/issues/13830 (done in https://github.com/chapel-lang/chapel/pull/13912)
 - [x] Decide what to do about compareExchange not matching the C interface -- https://github.com/chapel-lang/chapel/issues/13836, https://github.com/chapel-lang/chapel/issues/13837
