### ISSUE TITLE
Memory leaks

### ISSUE THREAD

**Issue by e-kayrakli** [chapel-lang/chapel#15623]
This meta-issue is a successor of other memory leak issues, particularly
https://github.com/chapel-lang/chapel/issues/7900.

Below is a checklist with particular bug reports with smaller reproducers for
each known leak, the tests that leak because of the bug, and the volume of the
leak in bytes.

## Summary

Total number of leaking tests: 25
Non-test leaks: 22
Likely number of bugs: 10

## Bugs

- [ ] Memory leak after starting to init the IO module early (https://github.com/Cray/chapel-private/issues/628)

#### Leaking tests

```
584  exits/albrecht/exitWithNoCall.chpl
584  exits/sungeun/exitWithNoParensNoArgs.chpl
```

---

- [ ] Memory leak in studies/dijkstra/driverEdgeBtw.chpl (https://github.com/Cray/chapel-private/issues/895)

#### Leaking tests
```
512  studies/dijkstra/driverEdgeBtw.chpl
```

---

- [ ] Fields with conditional array type expressions leak (https://github.com/chapel-lang/chapel/issues/14309)

#### Leaking tests

```
240  expressions/if/expr/inside-field.chpl
```

---

- [ ] Leak while creating an array of arrays using a for expression (https://github.com/chapel-lang/chapel/issues/15609)

#### Leaking tests
```
160  arrays/ferguson/from/iterator/for-yields-no-arrays.chpl
 80  arrays/shapes/skyline.when-empty.chpl
```

---

- [ ] Passing an "unnamed" array type to a function leaks (https://github.com/chapel-lang/chapel/issues/15611)

#### Leaking tests
```
160  arrays/deitz/runtime_types/test_array_type4.chpl
160  arrays/deitz/runtime_types/test_array_type3.chpl
 80  arrays/deitz/runtime_types/test_array_type1.chpl
 80  arrays/deitz/runtime_types/test_array_type2.chpl
 80  classes/bradc/arrayInClass/genericClassArray-anon.chpl
 ```

##### Note

  https://github.com/chapel-lang/chapel/issues/7891 refers to these leaks

---

- [ ] Type functions returning forall-like array type expressions leak (https://github.com/chapel-lang/chapel/issues/14318)

#### Leaking tests
```
80  functions/vass/type-and-param-function-arg-conversions.chpl
```

---

- [ ] Reductions over for expressions that yield associative domains leak (https://github.com/chapel-lang/chapel/issues/15612)

#### Leaking tests
```
128  associative/ferguson/plus-reduce-assoc.chpl
128  associative/bharshbarg/domains/reduceArrOfAssocDom.chpl
64  trivial/sidelnik/reduction.chpl
```

##### Note

  https://github.com/chapel-lang/chapel/issues/7897 refers to these leaks
  https://github.com/chapel-lang/chapel/issues/7896 refers to `reduction.chpl`

  The true nature of the bug may be more general than the issue title implies.

---

- [ ] memory leak for try/catch in defer block (https://github.com/chapel-lang/chapel/issues/12092)

#### Leaking tests
```
112  errhandling/psahabu/defer-throw-fatal.chpl
```

---

- [ ] Memory leaks from #12225 (and parallel error-handling in general (https://github.com/chapel-lang/chapel/issues/12511)

#### Leaking tests
```
96  errhandling/parallel/forall-wrap-first-error.chpl
48  errhandling/parallel/forall-throws.chpl
48  errhandling/parallel/forall-range-throws.chpl
48  errhandling/parallel/forall-throws-subtasks.chpl
```

---

- [ ] bare "new owned C()" leaks (https://github.com/chapel-lang/chapel/issues/11101)

#### Leaking tests
```
16  classes/initializers/postInit/class-nongeneric.chpl
16  classes/initializers/postInit/class-generic.chpl
```

##### Note
A potentially duplicate bug report:

Class allocations leak if they are not captured in a variable (https://github.com/chapel-lang/chapel/issues/15613)

### Other open leaks today

- Test leaks to be fixed with https://github.com/chapel-lang/chapel/pull/15614

```
80  types/records/sungeun/classInRecord.chpl
48  parallel/forall/reduce/intents/ri-6-user-instance.chpl
```

- Test that should remain leaking

```
8  memory/ferguson/test1.chpl
```

There's value in this leaking. The test checks whether the memory
allocated with Chapel's memory allocators can be cleaned with C
deallocators and vice-versa. When you allocate with Chapel and clean
with C, our memtracker can't see the deallocation and reports a leak.
It could be a good test for our memory tracker, because recently I
bumped into examples of such leaks.

Somehow, we can ignore this (and similar if there's any in the future)
and convert the leak into a correctness test. This can also be done
when we switch to memory-leak-is-a-bug once all the others are cleaned
up. We can have a `.memleaks` file that is checked after the run. If
the file is empty, then any leak should cause in test failing.

### Other issues of note

These we don't capture in our nightlies, but looks like we have futures for:

https://github.com/chapel-lang/chapel/issues/4953
https://github.com/chapel-lang/chapel/issues/6912

**Comment by e-kayrakli** [comment]
The only leak I am aware of is around non-inlined iterators that break. They are captured in futures and in issues https://github.com/chapel-lang/chapel/issues/4953, https://github.com/chapel-lang/chapel/issues/6540.
