### ISSUE TITLE
Chapel on Macs with M1 chips

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#17911]
This issue generally asks "How is Chapel doing on Macs with M1 chips?" where I think we mostly don't have much experience within the core team.  It would be good to be able to have access to one in-house to take stock of things.

We have had a user mention on Gitter that they were able to download from GitHub and build from source.  The GASNet's team seems to reflect this as well.

At present we know:
- [x] we don't have a homebrew bottle for M1 Macs (#17910)
  - brew audit on such Macs reports three issues:
     - [x] [a failure related to Qthreads](https://github.com/chapel-lang/chapel/issues/17910#issuecomment-950246280)
     - [x] [another related to Python](https://github.com/chapel-lang/chapel/issues/17910#issuecomment-950246280)
     - [x] another related to GMP (resolved)
- [x] the command `brew install --build-from-source chapel` results in `error: What kind of a Mac is this?`
- [ ] the GASNet team is seeing a failure on their M1 Mac runs (#17825)

**Comment by ronawho** [comment]
@bradcray I _think_, but am not positive that the first two major bullets are done. Do you agree?

**Comment by bradcray** [comment]
As far as I know (based on the Homebrew CI checks), but I don't have an M1 Mac to download and test on to be sure.  If you've verified them, it'd be fine with me to check those off.

**Comment by ronawho** [comment]
`brew install chapel` installed a bottle that works for me (passes hellos)

`brew install --build-from-source chapel` also gave me a working install.

**Comment by bradcray** [comment]
I'm going to go ahead and close this since we're in better shape with M1 Macs and the single remaining known issue is still open and can stand for itself.  (i.e., this issue was designed to bring attention to a handful of problems and I think has served that purpose).
