### ISSUE TITLE
Move the Built-in Types and Functions docs into the spec

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#18027]
On the sidebar in https://chapel-lang.org/docs/main/ we have "Built-in Types and Functions" . These sections are duplicative with spec sections, e.g.:

 https://chapel-lang.org/docs/main/builtins/ChapelRange.html
 https://chapel-lang.org/docs/main/language/spec/ranges.html#predefined-functions-on-ranges

We've historically had problems updating both of these so they can be in conflict.

In #16814 we reached the plan of moving the generated documentation for the internal modules (Built-in Types and Functions) into the appropriate spec sections. This issue tracks the task of actually doing it.

- [x] Atomics (PR #18443)
- [x] ChapelLocale (PR #18444)
- [x] OwnedObject (PR #20893)
- [x] Bytes (Engin) (PR #20622)
- [x] ChapelRange (Brad)
- [x] SharedObject (PR #20893)
- [X] ChapelArray (Andy) (PR #18908)
- [x] ChapelSyncvar (PR #21858)
- [x] String (Engin) (PR #20625)
- [x] ChapelComplex_forDocs (PR # #18488)
- [x] ChapelTuple (PR #20656)
- [x] weakPointer (PR #21861)

**Comment by mppf** [comment]
I think that https://docutils.sourceforge.io/docs/ref/rst/directives.html#include might be a way to achieve this

**Comment by mppf** [comment]
OK, I've created PR #18443 to migrate the Atomics docs and PR #18444 to migrate the Locales docs. After these two PRs are reviewed and merged, I'll have show how we can do this, and I'll be looking for others to take on the other modules here.

**Comment by bradcray** [comment]
I checked off ranges, which were done in https://github.com/chapel-lang/chapel/pull/20057

**Comment by jeremiah-corrado** [comment]
All built-in pages have been migrated, and the "Built-in Types and Functions" page itself was removed by: https://github.com/chapel-lang/chapel/pull/21861/

**Comment by bradcray** [comment]
Very cool!  Congratulations and thanks to all who contributed here, and particularly to Jeremiah for getting us across the finish line!
