### ISSUE TITLE
Memory.Initialization: Meta-Issue for Stabilization

### ISSUE THREAD

**Issue by benharsh** [chapel-lang/chapel#20330]
This issue exists to track and coordinate topics for stabilizing the Memory.Initialization module.

See https://github.com/chapel-lang/chapel/issues/16172 for the original module proposal and design discussion.

Module Naming:
- [x] https://github.com/chapel-lang/chapel/issues/20425

Function Signature Issues:
- [x] https://github.com/chapel-lang/chapel/issues/20411
- [x] https://github.com/chapel-lang/chapel/issues/20322
- [x] https://github.com/chapel-lang/chapel/issues/20328
- [x] https://github.com/chapel-lang/chapel/issues/20329
- [x] https://github.com/chapel-lang/chapel/issues/20334

Moving Array Elements:
- [x] https://github.com/chapel-lang/chapel/issues/20338
- [x] https://github.com/chapel-lang/chapel/issues/20339

Semantic Issues:
- [x] https://github.com/chapel-lang/chapel/issues/20410

**Comment by benharsh** [comment]
Please vote 👍  here if you wish to have a discussion on renaming this module

**Comment by benharsh** [comment]
Please vote 👍 and/or comment here if you wish to have a discussion concerning how this module should interact with Collections. We have a function to move elements between arrays. Should we do something similar for collections? Should collections be able to opt into an interface involving movement of data?

If there is enough support/interest, I will open a separate issue to track that discussion.

**Comment by vasslitvinov** [comment]
This module should replace `module ShallowCopy` in `modules/packages/Sort.chpl`

**Comment by bradcray** [comment]
> Please vote 👍 and/or comment here if you wish to have a discussion on renaming this module.

I gave this a thumbs-up because over time, I've felt slightly uncomfortable with the hierarchy in the `Memory` module, the fact that the top-level module is empty, and the fact that the siblings do such different things.  I think if I were to design it again myself today, I'd call the modules `MemInit` and `MemDiagnostics` and make them both top-level.  If this was discussed in the meeting I missed and nobody else felt similarly, though, I don't feel militant about it.  Just unconvinced that what we did was best.

> Please vote 👍 and/or comment here if you wish to have a discussion concerning how this module should interact with Collections. 

I don't know whether I care about this specific question, but I do continue to feel as though I'm not convinced we're in a state where we have a firm story for how a user would/should create their own collection type that can handle arbitrary element types (including arrays, other collections, non-nilable classes, non-default-initializable types, etc.).  Or if we do, I'm not sure that we've documented that story.  Would you consider that concern to be related to this question you're asking, or not?

**Comment by benharsh** [comment]
> I don't know whether I care about this specific question, but I do continue to feel as though I'm not convinced we're in a state where we have a firm story for how a user would/should create their own collection type that can handle arbitrary element types (including arrays, other collections, non-nilable classes, non-default-initializable types, etc.). Or if we do, I'm not sure that we've documented that story. Would you consider that concern to be related to this question you're asking, or not?

I don't think it's strictly related. I was thinking more about the specific case of optimizing bulk-movement of elements in a collection, and whether we should try and support some kind of interface for Collections (to match the functionality of ``moveInitializeArrayElements``).

**Comment by vasslitvinov** [comment]
> whether we should try and support some kind of interface for Collections (to match the functionality of moveInitializeArrayElements)

Are we allowed to wait until proper interfaces come online? :)

Without proper interfaces, we might not need to do much to support this functionality for collections:
* name this function in a non-array-specific way, and
* allow collections to introduce their own overloads

For example, call it `moveInitializeCollectionElements` or, for short, `moveInitializeElements` ? not to be confused with moveInitializeTheElement :)

What else would we like to have in such an interface?

One consideration is how to select a subset of elements to move-initialize. For an array, we can:
* create a slice, or
* pass a source and/or destination range.

For some other collections, ex. list, we do not have slices, however we can have src/dst ranges.

For yet other collections, ex. sets, subranges do not make sense.

Therefore a given collection will create overrides with its own flavors of arguments. In other words, we can standardize on "move-initialize the entire collection" and not so much on "move-initialize a subset of the elements".
