### ISSUE TITLE
Implement an error handling model

### ISSUE THREAD

**Issue by psahabu** [chapel-lang/chapel#4977]
### awaiting implementation
- [ ] standard library
  - [ ] investigate/remove `try!` and `halt()` from module code (#8452)
  - [ ] deprecate out error= functions
    - dependent on defer/deinit strategy, error memory management to store errors in vars
    - strategy:
      - rename and privatize them
      - change internal calls to the new name
      - make a wrapper with the old name, calling the privatized version
      - insert a compiler warning into the wrapper
    - [ ] update #7281
  - [ ] `try! this.lock();` -> `this.lock(); defer this.unlock();`
- [ ] add error handling to mason
- [ ] throwing from non-inlined iterators (#7134) 
  - MF note: fixing this will require possibly significant development effort (at least 1 day, maybe a week, maybe worse.) Also, one of my recent PRs added it-throws-inline.chpl and it-throws-noinline.chpl as tests.
  - [ ] ItemReader.these and channel.matches should be `throws` (turned off to work around failures in --baseline)
  - potential cause for memory leaks in the following tests:
    - `errhandling/parallel/forall-range-throws`
    - `errhandling/parallel/forall-throws-subtasks`
    - `errhandling/parallel/forall-throws`
- [ ] incorrect line number from uncaught error due to inlining (#7297)
- [ ] ensure `catch` clause lists go from specific to general
- [ ] initializer error handling (#6145)
  - should be possible to clean up partially initialized state in phase 1
  - could either call deinit or manually clean up initialized state in phase 2

### pending design
- [x] runtime errors
  - working conclusion: orthogonal to system resilience, waiting for use cases
- [ ] make `writeThis()` a throwing method?
  - MF: More difficult than initially thought, I/O code uses deferred syserr, would need defer.
- [ ] error memory management (#6428)
  - [ ] future: utilize Owned/Shared
  - note: Owned is a useful pattern for class cleanup on error
- [ ] should errors interact with stack tracing?
  - idea: `halt` raises an uncatchable error, which stores the stack trace

### testing and bugs
- [ ] add Curl testing (#7570)
- [ ] investigate failures on pgi (#5331)

### documentation
- [ ] chpldoc and prototype modules (#7489)
- [ ] update doc/rst/developer/bestPractices/ErrorWarningMessaging.txt
- [ ] reflect changes in CHIP 8
- [ ] language spec changes

# Overview

The goal of this effort is described in [CHIP 8](https://github.com/chapel-lang/chapel/blob/e6d55e0412ead8615b681d1a849b6243502a2776/doc/developer/chips/8.rst).

### AST, syntax
- [x] add try statements to the AST (#4918)
- [x] set up the parser to handle `try { }` syntax (#4933, #4940)
- [x] codegen the block statement within `try` (#4975)
- [x] add `throws` to function declaration AST, syntax (#5007, #5011)
- [x] add `try!` support to try AST, syntax (#5038)
- [x] add `throw` to function body AST, syntax (#5046)
- [x] add `catch` block to AST, syntax (#5655)

### lower error handling AST
- [x] add the pass (#5084 first draft, #5106 no-op)
  - after `functionResolution` and before `callDestructors`
- [x] inserting `out` formals into functions that throw (#5240)
- [x] halting on error for `try!` (#5240)
- [x] propagating errors for `try` (#5240)
- [x] handling errors with `catch` (#5655)
- [x] automatically deallocate Error objects that are consumed by `catch` (#5718)
- [x] nested `try` statements (#5718)
- [x] enclose `catch` filters with parentheses (#5721)

### Additional v1 work
- [x] create tests
- [x] update CHIP to reflect auto-propagation in Default mode (#5012)
- [x] 4 motivating examples as .future tests (#5012)
- [x] modify existing `Error` module - rename it to `SysError` (#5162)
- [x] create the default/strict mode compiler flag (#5655)
  - Note: we will need a strategy that allows for gradual adoption of the error handling strategy in the standard/internal/package modules.

### More completed
- [x] syntax highlighting for vim and highlight (#6277)
- [x] additional tests
  - [x] exercise default and strict mode
  - [x] other variables in scope (e.g. arrays) are freed appropriately (#5293)
- [x] print the `Error` type and `msg` if the error causes a halt
- [x] fix `throws` for generic function signatures (#6265)
- [x] use it in I/O library (#6963)
- [x] `defer` construct MF
- [x] properly direct errors from nested calls (#6607)
  - `var x = mayThrowError(); doSomething(mayThrowError())`
- [x] generic `Error` classes
- [x] syntax highlighting for emacs, ...
- [x] use `init` for `Error` (#7988)
- [x] exclude throwing out of `defer`, `deinit` (#8161)
  - such throws would be ubiquitous with no clear handling context

### parallelism and multilocale
- [x] error handling works within task constructs
- [x] errors work across `on` statements MF
- [x] `AsyncErrors` or other construct exists to encapsulate multiple errors
- [x] errors propagate out of tasks in `begin`
- [x] errors propagate out of tasks in `cobegin`/`coforall`
- [x] errors propagate out of tasks in `forall`

### design questions
- [x] fine-grained selection of error modes (#7055)
  - may fall back to the existing `pragma` based work
  - `prototype module`
- [x] `throw nil` should result in a `NilThrownError` (#7317)
  - PS
  - well known function calling into module, checks if `nil` before assigning to error variable
  - model on delete error
- [x] Should we divide SystemError into sub-classes for different kinds of errors? (#6297, #7218)
  - PS (start with FileNotFound factory)
  - yes, do it like Python does, e.g. FileNotFoundError is a subclass of SystemError with ENOENT.
- [x] unhandled error messages (#7013, #7119)
  - MF (name of error, location of creation)
  - use a mini-stacktrace format
```
 uncaught SystemError: No such file or directory in open with path "_test_cannotOpenMe.txt"
   myopen() at unableToOpenFile.chpl:1 (error created)
   main() at unableToOpenFile.chpl:5 (error not caught)
```
- [x] forall error type consistency (#7046)
  - PS
  - All ErrorGroups can only have 1 level underneath them
  - Errors from within a `forall` are always reported in an ErrorGroup
    - put inside lowerIterators?
- [x] error handling and sync blocks (#6853)
  - `sync` blocks throw, but some want more discussion
- [x] ErrorGroup or something else ? (#6854)
  - PS (#7127)
- [x] relax `try`, `throws`, `try!` (#6566)
  - continue to have relaxed try!
- [x] Should OOB access throw? (#6629)
  - no, leave it alone

### high priority
- fix bugs
  - [x] unhandled stderr.writeln() in default mode catch block #7130 (#7269)
  - [x] `Error` leaks with preemptive throws (#7331)
- [x] error handling primer
- [x] add tests
  - PS
  - [x] run `-memleaks` on error handling test directory
  - [x] throwing from iterators - add tests
- [x] single line assignments with throwing calls don't parse
  - MF
  - `var x = try! mayThrowError();`
  - `return try g();` a-la Swift
- [x] fix error handling with dynamic dispatch (#6315) - also error if you try to override with different throws-ness
  - MF
- [x] Migrate more standard modules to new error handling (look for `out error` or `error=`)
  - PS
  - [x] Spawn (#7166)
  - [x] HDFS (#7176)
  - [x] Regexp (#7153)
  - [x] FileSystem (#7174)
  - [x] Buffers (#7177)
  - [x] Path (#7177)
  - BigInt: only in `bigint` constructor, wait for initializer story
- [x] module code TODOs
  - PS
  - [x] adjust I/O tests with error= to use new mechanism (#7108)

**Comment by mppf** [comment]
More future steps:

 - [ ] add catch block to AST and syntax
 - [ ] lower error handling AST to other AST after functionResolution and before callDestructors
 - [ ] create tests

**Comment by benharsh** [comment]
@psahabu : could you add an entry here along the lines of "define a standard set of Error classes". For example, ``OutOfBoundsError``, ``FileNotFoundError``, etc.

**Comment by psahabu** [comment]
@benharsh Thanks, I've added that to Future Work.

**Comment by mppf** [comment]
- [ ] what happens when you `throw nil` or `throw nil:Error` ?

**Comment by psahabu** [comment]
@mppf
`throw nil` and `throw nil:Error` are basically empty returns because neither of them triggers error handling in the caller. This makes sense because error handling is set up to handle non-nil `Error` objects. Do you think will be a problem, or is it just user error?

Program:
```
proc throwNil() throws {
  writeln("throwing nil");
  throw nil;
}

proc throwNilError() throws {
  var e: Error;
  writeln("throwing nil Error");
  throw e;
}

try {
  throwNil();
  writeln("did not catch nil");
} catch {
  writeln("caught nil");
}

try {
  throwNilError();
  writeln("did not catch nil Error");
} catch {
  writeln("caught nil Error");
}
```

Output:
```
throwing nil
did not catch nil
throwing nil Error
did not catch nil
```

**Comment by mppf** [comment]
@psahabu - I'm concerned that if throwNil or throwNilError returned a record (say) that `throw nil` could return an record that hadn't been initialized? What I'd like to see is for `throw nil` to actually do nothing (ie be the same as if it wasn't there).

As far as whether or not it is user error, it may be... but I don't think it's reasonable for the compiler to find these cases at compile-time. So we could either:
 1) Define the behavior to be `throw nil` is a no-op
 2) Add runtime error checking to the `throw` so that
      a) halt if `nil` is thrown?
      b) change `nil` being thrown to throwing `NilThrownError` ?

I'd probably do 1 or 2a but it's not obvious to me which of those is the right path.

**Comment by psahabu** [comment]
@mppf -
I prefer 2b. The no-op strikes me as less intuitive since `throw` should always throw. It also might be harder for a user to realize their mistake if it were done by accident, as in the motivating example:

```
var e: Error;
// ...
throw e;
```

It's possible that the user's own error handling setup would reveal or even gracefully handle the `NilThrownError`, whereas the no-op might lead to a strange program state.

**Comment by mppf** [comment]
2b would be OK with me

**Comment by mppf** [comment]
- [ ] fix test/statements/defer/defer-manual-container-throws.chpl

**Comment by mppf** [comment]
- [ ] store & report line number information in errors, from the time that the error is created. Consider storing more stack trace information.

**Comment by mppf** [comment]
Re throwing `nil`, the current consensus direction is to make it throw a replacement error type, such as `NilThrownError`

**Comment by mppf** [comment]
@psahabu - I think we should close this issue and just work with other issues for the specific areas that need improvement. "Implement an error handling model" is something I think we've already done.

**Comment by psahabu** [comment]
@mppf Sounds reasonable to me.

**Comment by mppf** [comment]
Can you make sure there's an issue for each open checkbox? (Or if not ask me to do it)

**Comment by psahabu** [comment]
Will do.
