### ISSUE TITLE
Improving the LLVM backend

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#5043]
Future Work on LLVM Performance:
- [ ] Address the suggestions here: http://releases.llvm.org/4.0.0/docs/Frontend/PerformanceTips.html
- [x] loop vectorization hints for forall/vectorizeOnly loops. Potentially both llvm.loop.vectorize.enable and llvm.mem.parallel_loop_access are important. See codegenOrderIndependence in CForLoop::codegen(), which is only called for the C backend right now. PR #6533
- [x] improving type-based alias analysis metadata
  (use struct-path-aware TBAA)
  (TBAA generation may be turned off now; search for codegenMetadata)
- [x] indicating when a load is from a variable declared 'const'
  (see commit 6f0047ab7c90f456ab48f19ed59b58383a54e31f.
  This is tricky because during variable initialization, a
  const variable is mutable and could be read). Use LLVM invariant metadata. (#6706)
- [ ] investigate enabling the Polly polyhedral optimizer
- [x] (for --llvm-wide-opt) change to struct wide pointers (vs. packed) (#7487)
- [x] try -mllvm -use-cfl-aa for clang with --llvm-wide-opt. (It didn't seem to help; see #5533).

**Comment by coodie** [comment]
With current progress on loop vectorization one subtask might be added:

- Find cases where adding `llvm.mem.parallel_loop_access` metadata will impact generated code in positive way, like make some loop vectorizable, which would otherwise not get vectorized.

**Comment by mppf** [comment]
- [ ] upgrade to LLVM 4.0
- [ ] investigate using CreatLLVMCodGen, GetAddrOfGlobal to remove dependence on CodeGenModule.h (GetAddrOfGlobal added in 3.9). Note, this might require creating dummy globals/functions for getting type info out of clang, including GEP locations.

**Comment by mppf** [comment]
- [ ] investigate emitting a .o instead of a .bc
- [ ] investigate producing C code into a different module. While it's desireable to be able to use 'static inline' C functions in the runtime, we could achieve that by making these functions no longer have private linkage; by relying on LTO; or by combining the modules later (with code inspired by CloneModule).
- [ ] investigate producing a different LLVM module for each Chapel module
- [ ] investigate using the LLVM linker, LLD (note this is a separate project we do not currently bundle; recent version will be required for thinLTO support)
- [ ] investigate using thinLTO

**Comment by mppf** [comment]
- [ ] diagnose performance issues with --llvm vs. C backend. See performance graphs here: http://chapel.sourceforge.net/perf/chapcs/llvm/   Some notable current issues:
   - [ ] For Loop Time Compare test/statements/lydia/forVersusWhilePerf.chpl
   - [ ] While Loop Time Compare test/statements/lydia/forVersusWhilePerf.chpl
   - [ ] Elegance tuplesVSarrays test/studies/elegance/tuplesVSarrays.chpl
   - [ ] mandelbrot complex jacobnelson/mandelbrot-complex.chpl

**Comment by coodie** [comment]
Here is list of subtasks related to http://releases.llvm.org/4.0.0/docs/Frontend/PerformanceTips.html. 

- [ ] The basics:
  - [ ] Make sure that Modules contain both a data layout specification and target triple. 
  - [ ] For each function or global emitted, use the most private linkage type possible (private, internal or linkonce_odr preferably).
  - [ ] Avoid high in-degree basic blocks (e.g. basic blocks with dozens or hundreds of predecessors). 

- [ ] Place all alloca instructions related to function local variables in function entry block.
- [ ] Avoid loads and stores of large aggregate type, load individual fields from memory instead.
- [ ] Prefer zext over sext when legal
- [ ] Other things to consider:
  - [ ] Use ptrtoint/inttoptr sparingly (they interfere with pointer aliasing analysis), prefer GEPs
  - [ ] Prefer globals over inttoptr of a constant address - this gives you dereferencability information. In MCJIT, use getSymbolAddress to provide actual address.
  - [ ] Be wary of ordered and atomic memory operations
  - [ ] If calling a function which is known to throw an exception (unwind), use an invoke with a normal destination which contains an unreachable instruction.
  - [ ] Use profile metadata to indicate statically known cold paths, even if dynamic profiling information is not available - http://llvm.org/docs/LangRef.html#prof-metadata
  - [ ] When generating code for loops, try to avoid terminating the header block of the loop earlier than necessary.
  - [ ] In hot loops, consider duplicating instructions from small basic blocks which end in highly predictable terminators into their successor blocks.
  - [ ] When checking a value against a constant, emit the check using a consistent comparison type.
  - [ ] Avoid using arithmetic intrinsics unless you are required by your source language specification to emit a particular code sequence.
  - [ ] Avoid using the assume intrinsic until you’ve established that a) there’s no other way to express the given fact and b) that fact is critical for optimization purposes.
- [ ] Restricted operation semantics
  - [ ] Add nsw/nuw flags as appropriate. Some part of this has already been done, `nsw` and `nuw` flags are necessary to perform optimizations on loops.
  - [ ] Use fast-math flags on floating point operations if legal. 
- [ ] Describing Aliasing Properties
  - [ ] Add noalias/align/dereferenceable/nonnull to function arguments and return values as appropriate
  - [ ] Use pointer aliasing metadata, especially tbaa metadata, to communicate otherwise-non-deducible pointer aliasing facts
  - [ ] Use inbounds on geps. This can help to disambiguate some aliasing queries.
- [ ] Modelling memory effects
  - [ ] Mark functions as readnone/readonly/argmemonly or noreturn/nounwind when known
  - [ ] Use the lifetime.start/lifetime.end and invariant.start/invariant.end intrinsics where possible. Good place to start would be to see in what places does clang add these.
  - [ ] Mark invariant locations using !invariant.load and TBAA’s constant flags
- [ ] Pass Ordering. Currently Chapel uses -O3 clang pass, which is optimized for C++. Optimizing pass pipeline is probably quite big project, big enough to be done as entire GSoC project.
  - [ ] For languages with numerous rarely executed guard conditions (e.g. null checks, type checks, range checks) consider adding an extra execution or two of LoopUnswith and LICM to your pass order.
  - [ ] If you language uses range checks, consider using the IRCE pass. It is not currently part of the standard pass order.

- [ ] Add statistics pass, that would collect some information about llvm IR generated by Chapel related to issues above to make it easier to work on LLVM IR. One useful example would be collecting in-degree of basic blocks.

**Comment by mppf** [comment]
- [ ] turn on vectorization by default for --llvm

**Comment by mppf** [comment]
- [ ] consider adding parallel loop access metadata to function calls in order-independent loops

**Comment by coodie** [comment]
- [ ] Make calls from libc inlinable, eg. by changing the way code is linked/compiled.

**Comment by mppf** [comment]
See also issue #6993 which discusses upgrading LLVM versions & timing

**Comment by coodie** [comment]
While working on tuplesVSarray.chpl i noticed that issue with C outperforming LLVM was related to array aliasing and vectorizing properties. Running couple of experiments adding alias.scope and noalias metadata showed that in some cases this can give significant improvement in resulting code. This might be worth adding this metadata to LLVM IR for computation between arrays where known, like in this example:

```chpl
for i in dom do
   A[i] = B[i]*C[i];
```

This is going to generate code which has some store to `A` and loads from `B` and `C`, we'd like to add metadata saying that these stores and loads don't alias (provided that they really don't alias) using `noalias` and `alias.scope` as described in: http://llvm.org/docs/LangRef.html#noalias-and-alias-scope-metadata. Note that this might be very difficult to add, because arrays implementation in chapel is very complex and I'd expect quite a lot of cases where we cannot actually add this metadata (like when arrays actually alias or we cannot be sure of that).

- [ ] Add noalias and alias.scope metadata where possible.

**Comment by mppf** [comment]
- [ ] try dynamically linking Chapel with LLVM libraries to reduce the size of the binary, load times

**Comment by mppf** [comment]
- [ ] see https://stackoverflow.com/questions/22776391/why-does-clang-coerce-struct-parameters-to-ints - we should be doing ABI lowering (this matters in particular for struct arguments)

**Comment by mppf** [comment]
- [ ] separately time LLVM optimizations, .o generation, linking

**Comment by mppf** [comment]
It seems that adding noalias metadata for arrays would help Polly optimize loops in certain cases.

**Comment by mppf** [comment]
This issue is pretty out of date and now we have epics such as #15998. Furthermore, it's likely that we'll focus on those changes that solve a specific problem rather than updating to follow more guidelines. So I'm closing this issue.
