### ISSUE TITLE
Increase multi-locale performance testing problem sizes

### ISSUE THREAD

**Issue by ronawho** [chapel-lang/chapel#6323]
With performance improvements over the years, many of our problem sizes for multi-locale finish very quickly. We want to increase problem sizes for some cases to increase the stability and to just have longer running kernels. Here's some cases to look at increasing:

 - [x] MiniMD (punting based on https://github.com/chapel-lang/chapel/issues/6323#issuecomment-314817842)
 - [x] RA (increase number of updates) (#7522)
 - [x] Stencil PRK (#6380)
 - [x] Stream? (use default 1/4 mem instead of 8GB per node?) (punting based on https://github.com/chapel-lang/chapel/issues/6323#issuecomment-314819252)
 - [x] Lulesh? (punting since it's stable https://github.com/chapel-lang/chapel/issues/6323#issuecomment-314819543)

Note that we have to be careful and choose problem sizes that still run in a reasonable amount of time for gasnet-aries. We're thinking about retiring gn-mpi testing except for the streams so we don't have to worry about long running problem sizes in that configuration. We'll also want to choose problem sizes that make sense for chapcs/cluster multi-locale performance testing as well.

**Comment by ronawho** [comment]
@benharsh thoughts on increasing MiniMD? It's running around 10 second for ugni right now and it seems stable in nightly testing, so I'm thinking we should just leave it be for now.

**Comment by benharsh** [comment]
I'm fine with leaving it alone for now. It should be running *much* faster, but until then I believe the current problem size is sufficient for studying overhead.

**Comment by ronawho** [comment]
Going to punt on stream too. Sticking with 8GB for stream allows it to fit into KNL's HBM, and stream is also pretty stable in nightly

**Comment by ronawho** [comment]
I guess lulesh is pretty stable too. Punt on that as well?

**Comment by ronawho** [comment]
I think we're done with this for now
