### ISSUE TITLE
Consider using processor atomics for remote coforalls EndCount

### ISSUE THREAD

**Issue by ronawho** [chapel-lang/chapel#6356]
https://github.com/chapel-lang/chapel/pull/2451 forced "local" coforalls to use processor atomics for better performance. Processor atomics are faster than network atomics for operations that are only done on a single locale, so it makes sense to have local coforalls use processor atomics. We left "remote" coforalls (coforall+on) using network atomics with the thought that the end count will mostly be manipulated by remote locales, in which case network AMOs will be faster than a remote-fork+processor atomic.

So for someting like:

```chapel
coforall loc in Locales do on loc { }
```

the spawning task will increment the EndCount once for each task, and then do a waitFor, while remote tasks will decrement the EndCount when they're done running. The remote tasks decrementing the EndCount should benefit from using network atomics, but it seems doing the network AMOs possibly including the waitFor hurts things overall. 

Surprisingly, switching to using processor atomics (switching `forceLocalTypes` to `gTrue` in https://github.com/chapel-lang/chapel/blob/master/compiler/AST/build.cpp#L1584) results in significantly better performance for some multi-locale codes including stream, RA, Lulesh , and prk stencil

Here's a few sample timings:

| Benchmark   | u+q default  | u+q procssor atomic EndCount |
| ----------- | ------------ | ---------------------------- |
| lulesh      | 3.35s        | 2.9s                         |
| stencil prk | 98 GFlops/s  | 104 GFlops/s                 |
| stencil-opt | 193 GFlops/s | 235 GFlop/s                  |
| prom stream | 440 GB/s     | 640 GB/s                     |

Here's a full list of perf differences: https://gist.github.com/ronawho/719c6f6a470b10599d73f7b5d36c57d9

A lot of these benchmarks have pretty quick running kernels (noted in https://github.com/chapel-lang/chapel/issues/6323), so we should increase them before making this change or at least evaluate the benefit of this change for different length kernels.

The relatively large impact of changing endcounts also indicates that we should really implement the "bounded-coforall" (https://github.com/chapel-lang/chapel/pull/5018) optimization for remote coforalls as well. 

We should also create a remote coforall microbenchmark to help determine the impact of network vs. processor atomic EndCounts.

TODOs:

 - [x] create a microbenchmark for coforall+on (#6378)
 - [x] implement bounded coforall optimization for remote coforalls (#6357, #6419)
 - [x] avoid manipulating `EndCount.taskCnt` when possible (`countRunningTasks=false`, bounded-coforall)
 - [ ] increase multi-locale problem sizes (#6323)
 - [ ] re-evaluate the performance benefit of using processor atomics for remote EndCounts

**Comment by ronawho** [comment]
Ok, so for the microbenchmark there is a 2X performance benefit to using processor atomics for the EndCount

```chapel
use Time;

config const numTrials = 100000;
config const printTimings = true;

proc main() {
  var t: Timer;

  t.start();
  for 1..numTrials do
    coforall loc in Locales do on loc {}
  t.stop();

  if printTimings {
    writeln("Elapsed time: ", t.elapsed());
  }
}
```

| -nl | u+q default | u+q procssor atomic EndCount |
| --- | ----------- | ---------------------------- |
| 1   |  .13s       |  .13s                        |
| 2   | 1.11s       |  .48s                        |
| 4   | 2.02s       |  .84s                        |
| 8   | 3.75s       | 1.59s                        |
| 16  | 7.25s       | 3.15s                        |
| 32  | 14.6s       | 6.35s                        |

Granted that's for 100,000 trials, so each individual coforall is pretty quick, so it's not obvious why this has such an impact on real benchmarks, but so be it. I'll add this micro-benchmark to the 16-node-xc suite at some point

**Comment by ronawho** [comment]
It turns out that for a coforall+on stmt `upEndcount` actually updates 2 network atomics under ugni. https://github.com/chapel-lang/chapel/commit/0007e325d8c6ccef4cd0908628fbeb50c04a904e changed `EndCount.taskCnt` to be a network atomic under ugni, so we update our `EndCount.i` and `EndCount.taskCnt` AMOs for each `upEndCount` invocation.

I'm having a hard time figuring out how that commit helped things. So far as I know, upEndCount is only called on the spawning locale, which will also own the EndCount class, so I'm not seeing how there would be any communication needed to update `EndCount.taskCnt` in the first place. i.e. I don't understand how `e.taskCnt = e.taskCnt + 1;` actually resulted in any communication because so far as I understand `e` would have lived on that node calling `upEndCount`. Anyways, despite my inability to grok how that helped, it did reduce comm counts for a few tests at that time, but I don't think it's needed anymore. Furthermore, making taskCnt a non-aotmic int takes the 16 node timings from 7.25 seconds down to 5.0 seconds, which is pretty substantial.

**Comment by ronawho** [comment]
@sungeunchoi and/or @gbtitus could one of you explain how https://github.com/chapel-lang/chapel/commit/0007e325d8c6ccef4cd0908628fbeb50c04a904e improved comm counts? For the non-ugni case it looks like it really just changed `upEndCount` from:

```chapel
e.i.add(1);
e.taskCnt = e.taskCnt + 1;
```

to 

```chapel
on e {
  e.i.add(1);
  e.taskCnt += 1;
}
```

but at least for coforall+on stmts, `upEndcount` will only be called on the spawning locale (i.e. the locale that owns `e`, so I don't see how that could actually get rid of communication. I feel like I'm missing something obvious here.

**Comment by ronawho** [comment]
Misc note: It appears that for uncontended atomics, there's not a huge perf difference between using network vs. processor atomics, so there's probably no huge advantage to using network atomics for EndCounts since they won't be highly contended. At least there's not a big difference for a simple test that declares an atomic on locale 0, and updates it from locale 1.

```chapel
use Time;

config const numTrials = 100000;
config const printTimings = true;
config const contended = false;
config const taskPar = if contended then here.maxTaskPar else 1;

proc timeit(type atomicType) {
  var t: Timer;
  var atomicVar: atomicType;

  t.start();
  on Locales[1] {
    coforall 1..taskPar do
      for 1..numTrials do
        atomicVar.add(1);
  }
  t.stop();

  if printTimings {
    writeln("Elapsed time for ", atomicType:string, " : ", t.elapsed());
  }
}

proc main() {
  timeit(chpl__networkAtomicType(int));
  timeit(chpl__processorAtomicType(int));
}
```

| contended | processor | network |
| --------- | --------- | ------- |
| no        |  .21s     | .14s    |
| yes       | 3.72s     | .20s    |

For contended atomics, network atomics have a huge performance advantage, but it might not be too far-fetched to want to always use processor atomics for coforall+on EndCounts, though we have some more work/investigation to do before making that call

**Comment by gbtitus** [comment]
At the time [0007e32](https://github.com/chapel-lang/chapel/commit/0007e325d8c6ccef4cd0908628fbeb50c04a904e) was committed, was the upEndCount done from the child task rather than the parent?  That would explain why it was beneficial to use a network atomic.

**Comment by gbtitus** [comment]
For a single remote atomic update, certainly a network atomic op will be faster than an executeOn and processor atomic op, even if the executeOn is a "fast" one.  However, that may not necessarily matter for a coforall-on across locales.  With small on-bodies and large locale counts, both of which would tend to increase the effect of overhead, maybe one could see an effect for downEndCount(), which is remote.  But by "large locale counts" I'm thinking of scales on the order of 100s or 1000s or more compute nodes, which we pretty much never run except for in release scaling testing, and not much then.  And for large scales like that, we'll probably find ourselves wanting to use some kind of tree-based initiate and sync for coforalls anyway, which would effectively eliminate contention on a single node and/or counter.

Note that if the executeOn isn't "fast", though, then the overhead goes way up and could be visible at much smaller scales.

**Comment by ronawho** [comment]
>At the time [0007e32](https://github.com/chapel-lang/chapel/commit/0007e325d8c6ccef4cd0908628fbeb50c04a904e) was committed, was the upEndCount done from the child task rather than the parent?  That would explain why it was beneficial to use a network atomic.

That was my first thought too, but for coforalls, upEndCount is called from the parent task. 

Think I figured this out now. It's not the coforall that https://github.com/chapel-lang/chapel/commit/0007e325d8c6ccef4cd0908628fbeb50c04a904e was addressing. It was removing a comm count for a begin. A remote begin was updating the "main" EndCount, which does require communication. So we may want to continue to have begins use network atomics, but we can special case coforalls now to avoid doing it in the case where we know upEndCount will only modify a local EndCount

**Comment by gbtitus** [comment]
I'm curious what your microbenchmark would do as we scale up to, say, 1024 nodes or even more if we can get them.  Do you have a NERSC/cori account?

**Comment by ronawho** [comment]
>For a single remote atomic update, certainly a network atomic op will be faster than an executeOn and processor atomic op, even if the executeOn is a "fast" one. However, that may not necessarily matter for a coforall-on across locales. With small on-bodies and large locale counts, both of which would tend to increase the effect of overhead, maybe one could see an effect for downEndCount(), which is remote. But by "large locale counts" I'm thinking of scales on the order of 100s or 1000s or more compute nodes, which we pretty much never run except for in release scaling testing, and not much then. And for large scales like that, we'll probably find ourselves wanting to use some kind of tree-based initiate and sync for coforalls anyway, which would effectively eliminate contention on a single node and/or counter.

For the microbenchmark I showed (and for EndCount updates), the fast-on optimization triggers (at least since https://github.com/chapel-lang/chapel/pull/4008) so the processor atomic updates will run in the comm-handler directly instead of spawning a task. Agreed that the story would be different if it wasn't a fast-on, but I was still surprised that an uncontended fast-on+processor-atomic was even relatively close to the performance of a network-atomic 

And yeah, for large locale counts we'll definetly want some sort of tree-based spawning, but I have to admit I was surprised how much of an impact mucking with the EndCount types had on performance for a lot of our 16-node  benchmarks.

**Comment by ronawho** [comment]
>I'm curious what your microbenchmark would do as we scale up to, say, 1024 nodes or even more if we can get them.  Do you have a NERSC/cori account?

No, I don't, but agreed that we'll want to investigate at larger node counts. To start I can at least go to some larger internal machines and get numbers for up to ~500 nodes. A

I think the scalability studies are only needed for deciding between processor vs. network atomic for the coforall+on EndCount. There's still a lot of room for scale-agnostic improvements beyond that (non-atomic taskCnt for coforall+on and bounded-coforall optimization for remote coforalls)

**Comment by ronawho** [comment]
And by that I just meant that I want to implement the other optimizations first, before revisiting the question of whether we should use processor or network atomics for coforall+on EndCounts.

**Comment by gbtitus** [comment]
Probably the cost of launching an actual task for the on-body, even an empty one, is so large that it hides the difference between using an uncontended fast-on+processor-atomic and using a network-atomic?  I wonder what we'd see for a nanobenchmark that just did either a squillion remote network-atomics or a squillion remote fast-on-processor-atomics (hint, hint).  (One at a time from the initiating node, no on-node parallelism, since that's the usage model for the coforall-across-nodes.)

**Comment by gbtitus** [comment]
My bad -- the 2nd benchmark here already is the nanobenchmark I was seeking in the above comment!

**Comment by ronawho** [comment]
Alright, so here are the new timings for `parallel/taskCompare/elliot/empty-chpl-remote-taskspawn.chpl` after the bounded remote coforall optimization (#6419):

| -nl | u+q AMO | u+q procssor |
| --- | ------- | -------------|
| 1   |   .54s  |   .54s       |
| 2   |  3.36s  |  2.34s       |
| 4   |  4.66s  |  4.02s       |
| 8   |  7.54s  |  7.54s       |
| 16  | 13.44s  | 14.72s       |
| 32  | 25.04s  | 28.18s       |

Using a network atomic EndCount is now faster than a processor EndCount after 8 locales, I'm going to close this issue for now.

http://chapel.sourceforge.net/perf/16-node-xc/?graphs=emptyremotetaskspawntime will continue to track processor vs network atomic EndCounts
