### ISSUE TITLE
issues blocking Collections module

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#7276]
- [ ] #6912 -- breaking from iters does not call destructors
- [x] #7003 -- licm dynamic dispatch bug (elliot)
- [ ] #6998 -- dynamically dispatched parallel iterators don't work
- [x] #6542 -- not capturing dynamically dispatched calls causes compiler segfault (michael)
- [ ] #7282 -- fifo deadlock (elliot)

**Comment by ronawho** [comment]
3/5 of these are really embarrassing dynamic dispatch bugs that I think we should try to get fixed for this release. 1 should be fixed, and michael owns another, but we're still looking for an owner for  #6998 (dynamic dispatch for parallel iterators causes compiler seg fault). 

I think @vasslitvinov is the natural owner for that, but if anybody else can beat him to it, that'd be good

**Comment by LouisJenkinsCS** [comment]
Is there anything you guys want me to do?

**Comment by mppf** [comment]
Since the collections module is already merged, and the remaining TODOs here have their own issues, I'm going to close this issue. It will remain available for historical / linking purposes.
