### ISSUE TITLE
Convert standard/internal/package modules to initializers

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#8301]
This issue is intended to capture the work remaining to convert the modules/ directory's
contents over from constructors to initializers.  This is an effort I've been working on during
spare-time cycles over the past month or so and have gotten pretty close on.  Here are
cases that still need work:

### Internal
- [x] **OwnedObject.chpl:** In its purest form, this is failing because the compiler-provided chpl__autoCopy/initCopy() routines don't support passing RHS arguments by `ref` to copy initializers.  We could work around this if necessary, but I've been dragging my feet in hopes of not requiring this to be a special-case.  See issue #8234.
- [x] **first-class functions** #9535
- [x] **Array, Domain, and Distribution record wrappers:** Tricky due to existing initCopies returning a different type. (#9313)
- [x] **Reductions** (#9315)
- [x] **Atomics**
- [x] **Tuples**
- [x] **SharedObject.chpl:** This is ready to go in PR #8170
- [x] *all modules supporting domain maps, domains, arrays:* These ran afoul of limitations in our current initializer story, being discussed in issue #8283.
- [x] **Range.chpl:** Originally ran into a promotionType issue that BHarsh resolved, and is ready for another look.  In its current form, likely to run into limitations relating to conditional expressions and compiler-provided initializers, but the conditional expression has also been noted as being arguably illegal (due to calling a method), so needs a look.
- [x] **ChapelSyncVar.chpl:** Originally ran into an issue with calling `new` on the result of a type function (issue #7935), now believed to be fixed for this case and ready for another look.
- [x] **String.chpl:** These run into a number of tricky cases due to the compiler's built-in support for strings (e.g., string literals like "hello" get special treatment in the compiler). Resolved by #9217.

### Standard
- [x] IO.file and other miscellaneous records in IO module
- [x] List
- [x] Regexp.regexp
- [x] Random
- [x] Loc* classes in distributions (#9314)
- [x] **Buffers.chpl:** Simply needs post-review edits and merge; however, current testing is arguably insufficient to have confidence in copy initializers.

### Package
- [x] **DistributedBag.chpl / DistributedQueue.chpl:** Same as above.

**Comment by bradcray** [comment]
Filtering out the cases known not to be converted above (domain maps, OwnedObject, string), I got failures for the following tests, some of which are designed to ensure constructors are still working.  The only case I think I detected which was left unconverted in modules was `RecordParser` which I'll take a quick look at:

* classes/constructors/base-class-generic-args.chpl
* classes/constructors/base-initializer.chpl
* classes/constructors/brad-dispatch.chpl
* classes/constructors/error-constructor-return-type.chpl
* classes/constructors/generic-uninit-field-constructors.chpl
* classes/constructors/record-var-invokes-user-constructor.chpl
* classes/dinan/generic_constructor.chpl
* classes/dinan/init_before_userdef_constructor.chpl
* classes/dinan/user_def_default_constructor.chpl
* classes/dinan/user_def_default_constructor_const.chpl
* classes/dinan/user_def_unique_constructor.chpl
* classes/dinan/user_def_unique_constructor_const.chpl
* classes/hilde/inheritance/constructors.chpl
* classes/initializers/record-with-call-init.chpl
* classes/initializers/compilerGenerated/had_constructor.chpl
* classes/initializers/compilerGenerated/inherits_constructor.chpl
* classes/initializers/compilerGenerated/parent_inherits_constructor.chpl
* classes/initializers/errors/bothGeneric-lhsConsRhsInit.chpl
* classes/initializers/errors/bothGeneric-lhsInitRhsCons.chpl
* classes/initializers/errors/generic-lhsConsRhsInit.chpl
* classes/initializers/errors/generic-lhsConsRhsInit2.chpl
* classes/initializers/errors/generic-lhsInitRhsCons.chpl
* classes/initializers/errors/generic-lhsInitRhsCons2.chpl
* classes/initializers/errors/lhsConsRhsInit.chpl
* classes/initializers/errors/lhsInitRhsCons.chpl
* classes/moduleScope/mod-init.chpl
* classes/stonea/constAndParamInConstructor.chpl
* classes/vass/old-destructor-name.chpl
* compflags/lydia/noUseNoinit/noinitSkippedCase (compopts: 1).chpl
* compflags/lydia/noUseNoinit/noinitSkippedCase (compopts: 2).chpl
* compflags/lydia/noUseNoinit/noinitSkippedCase (compopts: 3).chpl
* compflags/lydia/noUseNoinit/recordHasClassField.chpl
* distributions/bradc/assoc/userAssoc-array-domain-zipper.chpl
* distributions/bradc/assoc/userAssoc-array-noelt.chpl
* distributions/bradc/assoc/userAssoc-array-priv-check.chpl
* distributions/bradc/assoc/userAssoc-basic-array.chpl
* distributions/bradc/assoc/userAssoc-basic-domain.chpl
* distributions/bradc/assoc/userAssoc-dom-operations.chpl
* distributions/bradc/assoc/userAssoc-domain-priv-check.chpl
* errhandling/ferguson/err-return-default.chpl
* functions/iterators/bharshbarg/recurseHeapBug.chpl
* io/tzakian/recordReader/test.chpl
* reductions/diten/deleteReductionClass.chpl
* release/examples/spec/Classes/simpleConstructors.chpl
* release/examples/spec/Generics/constructorsForGenericFields.chpl
* release/examples/spec/Records/recordCreation.chpl
* release/examples/spec/Records/recordDeinitializer.chpl
* studies/amr/advection/amr/AMR_AdvectionCTU_driver.chpl
* studies/comd/elegant/arrayOfStructs/CoMD.chpl
* studies/comd/llnl/CoMD.chpl
* studies/labelprop/labelprop-tweets.chpl
* studies/shootout/submitted/chameneosredux.chpl
* studies/shootout/submitted/chameneosredux2.chpl
* types/records/const-checking/modifies-const-fields-of-this.chpl
* types/records/ferguson/copy-report.chpl
* types/records/ferguson/copy-init/old-ctor-concrete.chpl
* users/shetag/objRefAsFormArg.chpl
* users/vass/km/array-of-records-crash-1.chpl
* users/vass/km/array-of-records-crash-2.chpl
* users/vass/km/array-of-records-crash-2.explicit-type.chpl

**Comment by lydia-duncan** [comment]
The following have a counterpart in the initializers directory:
- [ ]     classes/constructors/base-class-generic-args.chpl
- [ ]     classes/constructors/base-initializer.chpl
- [ ]     classes/constructors/brad-dispatch.chpl
- [ ]     classes/constructors/error-constructor-return-type.chpl
- [ ]     classes/constructors/generic-uninit-field-constructors.chpl
- [ ]     classes/constructors/record-var-invokes-user-constructor.chpl
- [ ]     classes/dinan/generic_constructor.chpl
- [ ]     classes/dinan/init_before_userdef_constructor.chpl
- [ ]     classes/dinan/user_def_default_constructor.chpl
- [ ]     classes/dinan/user_def_default_constructor_const.chpl
- [ ]     classes/dinan/user_def_unique_constructor.chpl
- [ ]     classes/dinan/user_def_unique_constructor_const.chpl
- [ ]     classes/hilde/inheritance/constructors.chpl
- [ ]     classes/stonea/constAndParamInConstructor.chpl

The following are initializer tests with intentional constructors, that should be removed when constructors are fully deprecated and removed.
- [ ]     classes/initializers/record-with-call-init.chpl
- [ ]     classes/initializers/compilerGenerated/had_constructor.chpl
- [ ]     classes/initializers/compilerGenerated/inherits_constructor.chpl
- [ ]     classes/initializers/compilerGenerated/parent_inherits_constructor.chpl
- [ ]     classes/initializers/errors/bothGeneric-lhsConsRhsInit.chpl
- [ ]     classes/initializers/errors/bothGeneric-lhsInitRhsCons.chpl
- [ ]     classes/initializers/errors/generic-lhsConsRhsInit.chpl
- [ ]     classes/initializers/errors/generic-lhsConsRhsInit2.chpl
- [ ]     classes/initializers/errors/generic-lhsInitRhsCons.chpl
- [ ]     classes/initializers/errors/generic-lhsInitRhsCons2.chpl
- [ ]     classes/initializers/errors/lhsConsRhsInit.chpl
- [ ]     classes/initializers/errors/lhsInitRhsCons.chpl
- [ ]     classes/moduleScope/mod-init.chpl (This one should have parts of it removed but not all)

The following were intentionally skipped in #6530, some to intentionally remove later and the others to update when other features were added (noinit in this case)
- [ ]     classes/vass/old-destructor-name.chpl
- [ ]     compflags/lydia/noUseNoinit/noinitSkippedCase (compopts: 1).chpl
- [ ]     compflags/lydia/noUseNoinit/noinitSkippedCase (compopts: 2).chpl
- [ ]     compflags/lydia/noUseNoinit/noinitSkippedCase (compopts: 3).chpl
- [ ]     compflags/lydia/noUseNoinit/recordHasClassField.chpl
- [ ]     types/records/const-checking/modifies-const-fields-of-this.chpl
- [ ]     types/records/ferguson/copy-init/old-ctor-concrete.chpl

These rely on domains/distributions/arrays getting updated for initializers
- [ ]     distributions/bradc/assoc/userAssoc-array-domain-zipper.chpl
- [ ]     distributions/bradc/assoc/userAssoc-array-noelt.chpl
- [ ]     distributions/bradc/assoc/userAssoc-array-priv-check.chpl
- [ ]     distributions/bradc/assoc/userAssoc-basic-array.chpl
- [ ]     distributions/bradc/assoc/userAssoc-basic-domain.chpl
- [ ]     distributions/bradc/assoc/userAssoc-dom-operations.chpl
- [ ]     distributions/bradc/assoc/userAssoc-domain-priv-check.chpl
- [ ]     studies/labelprop/labelprop-tweets.chpl

I think this one would work once reductions explicitly use default initializers, so would wait until then
- [ ]     reductions/diten/deleteReductionClass.chpl

Should be updated once we decide to deprecate constructors
- [ ]     release/examples/spec/Classes/simpleConstructors.chpl
- [ ]     release/examples/spec/Generics/constructorsForGenericFields.chpl
- [ ]     release/examples/spec/Records/recordCreation.chpl
- [ ]     release/examples/spec/Records/recordDeinitializer.chpl
- [ ]     studies/shootout/submitted/chameneosredux.chpl
- [ ]     studies/shootout/submitted/chameneosredux2.chpl

Issue with nested records and classes with generics
- [ ]     studies/amr/advection/amr/AMR_AdvectionCTU_driver.chpl

Needs support of error handling statements in initializers
- [ ]     studies/comd/elegant/arrayOfStructs/CoMD.chpl
- [ ]     studies/comd/llnl/CoMD.chpl

Has a version of the constructors that are initializers commented out, probably ready for the switch.
- [ ]     types/records/ferguson/copy-report.chpl

Bug with nil as the default value for a class initializers
- [ ]     users/shetag/objRefAsFormArg.chpl

Semantic question on how to update this test prevented it from getting updated earlier.
- [ ]     users/vass/km/array-of-records-crash-2.chpl
- [ ]     users/vass/km/array-of-records-crash-2.explicit-type.chpl

I don't see any reason why these couldn't be updated now
- [ ]     errhandling/ferguson/err-return-default.chpl
- [ ]     functions/iterators/bharshbarg/recurseHeapBug.chpl
- [ ]     users/vass/km/array-of-records-crash-1.chpl

**Comment by benharsh** [comment]
Closing now that initializers are on by default and a warning is emitted for constructors.
