### ISSUE TITLE
Create a set of core communication performance tests

### ISSUE THREAD

**Issue by ronawho** [chapel-lang/chapel#8305]
Create a set of core/fundamental communication performance tests. These should allow us to compare the performance of various comm layers and track improvements/regressions to core idioms over time. 

Here's the current list of benchmarks that we’d like to add:
 - [ ] gets/puts
    - [x] small (64-bit, say) (done in #8520)
    - [x] large (1 mb?)
    - [ ] strided
 - [x] on-stmts
    - [x] fast (done directly by AM handler, no runtime task needed) (done in #8520)
    - [x] small (single transaction to initiate) (done in #8520)
    - [x] large (multi-transaction to initiate, i.e. for arg bytes)
 - [x] atomic operations (network and processor) (done in #8520)
 - [x] coforall-on idiom (done in #6378)
 - [x] start-up cost (done in #8123)
 
For all of those we should probably track varying levels of concurrency (serial, 1/4, maxed out) and think about if there's some way we can test non-blocking gets/puts. We should also track different variants including:
 - [x] many-to-one (emphasizes target-side limitations) (done in #8520)
 - [ ] one-to-many (emphasizes source-side limitations)
 - [x] balanced (emphasizes network limitations and/or interference between source-oriented and target-oriented mechanisms)

 Not as fundamental, but might be worth tracking:
 - [x] barrier performance (done in #8504)
 - [ ] concurrent array creation performance (because of dynamic array registration)

Note that some larger benchmarks stress some of these components already (and allow us to compare to references in other languages): 
 - ISx tests concurrent array creation, large all-to-all puts, barriers, and probably more
 - ra-on tests performance of on-stmts 
 - ra-atomic tests performance of atomic operations
 - ra-rmo tests performance of many small gets/puts
 - stream (particularly at scale) tests the coforall-on idiom

**Comment by ronawho** [comment]
Closing, we've been pretty happy with the set of benchmarks we have currently, and expect we'd add more on-demand as we hit performance issues instead of proactively adding more.
