### ISSUE TITLE
Vagrant TODOs

### ISSUE THREAD

**Issue by ronawho** [chapel-lang/chapel#8531]
Misc vagrant related items that I timed out getting to:

 - [x] Upgrade ubuntu boxes (and move zezty to EOL) (done with #8589)
 - [x] Move omnios to EOL (looks like omnios has development has stopped) (done with #8589)
 - [x] Fix some configs that fail with `chapeldefaultcheck.sh` (done with #8590)
 - [x] Add a `chapelfullcheck.sh` that forces `CHPL_GMP=gmp` and `CHPL_REGEXP=re2` (done with #8591)
 - [ ] Build with WARNINGS=1 to catch build warnings
 - [ ] Run vagrant as part of nightly testing

**Comment by ronawho** [comment]
Closing, the remaining work here is to add automated testing, and that's better captured by https://github.com/Cray/chapel-private/issues/2000
