### ISSUE TITLE
Convert initialize methods to postinit

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#8980]
These are the files that have `initialize(` still within them.  The `initialize()` method is basically covered by `postinit()` now, so these files should use that instead.

Passed testing:
- [x] test/arrays/marybeth/CMO_array.chpl:  proc initialize() {
- [x] test/associative/bradc/localeDom/assocLocales3.chpl:  proc initialize() {
- [x] test/classes/deitz/class-constructor/class_construct1.chpl:  proc initialize() {
- [x] test/distributions/diten/Dimensional.chpl:  proc initialize() {
- [x] test/distributions/diten/Dimensional.chpl:  proc initialize() {
- [x] test/expressions/bradc/condExprInClassInit.chpl:  proc initialize() {
- [x] test/param/nelson/coercion.chpl:  proc initialize() {
- [x] test/studies/amr/lib/level/LevelVariable_def.chpl:  proc initialize() {
- [x] test/studies/hpcc/common/bradc/BradsBlock1D.chpl:  proc initialize() {
- [x] test/studies/hpcc/common/bradc/BradsBlock1D.chpl:  proc initialize() {
- [x] test/studies/hpcc/common/bradc/BradsBlock1D.chpl:  proc initialize() {
- [x] test/studies/hpcc/common/bradc/BradsBlock1DPar-deitzditen.chpl:  proc initialize() {
- [x] test/studies/hpcc/common/bradc/BradsBlock1DPar-deitzditen.chpl:  proc initialize() {
- [x] test/studies/hpcc/common/bradc/BradsBlock1DPar-deitzditen.chpl:  proc initialize() {
- [x] test/studies/hpcc/common/bradc/BradsBlock1DPar-deitzditen.chpl:  proc initialize() {
- [x] test/studies/hpcc/common/bradc/BradsBlock1DPar-ideal.chpl:  proc initialize() {
- [x] test/studies/hpcc/common/bradc/BradsBlock1DPar-ideal.chpl:  proc initialize() {
- [x] test/studies/hpcc/common/bradc/BradsBlock1DPar.chpl:  proc initialize() {
- [x] test/studies/hpcc/common/bradc/BradsBlock1DPar.chpl:  proc initialize() {
- [x] test/studies/madness/aniruddha/madchap/mytests/par-compress/MRA.chpl:    proc initialize() {
- [x] test/studies/madness/aniruddha/madchap/mytests/par-reconstruct/MRA.chpl:    proc initialize() {
- [x] test/studies/madness/aniruddha/madchap/mytests/par-refine/MRA.chpl:    proc initialize() {
- [x] test/studies/madness/aniruddha/madchap/recordBug/FTree.chpl:    proc initialize() {
- [x] test/studies/madness/aniruddha/madchap/recordBug/MRA.chpl:    proc initialize() {
- [x] test/studies/madness/common/FTree.chpl:    proc initialize() {
- [x] test/studies/madness/common/MRA.chpl:    proc initialize() {
- [x] test/studies/madness/dinan/mad_chapel/FTree.chpl:    proc initialize() {
- [x] test/studies/madness/dinan/mad_chapel/MRA.chpl:    proc initialize() {
- [x] test/studies/shootout/nbody/bradc/nbody-blc-ref.chpl:  proc initialize() {
- [x] test/studies/shootout/nbody/bradc/nbody-blc-slice.chpl:  proc initialize() {
- [x] test/studies/shootout/nbody/bradc/nbody-blc-zip.chpl:  proc initialize() {
- [x] test/studies/shootout/nbody/bradc/nbody-blc.chpl:  proc initialize() {
- [x] test/multilocale/bradc/needMultiLocales/writeThisUsingOn.chpl:  proc initialize() {
- [x] test/multilocale/diten/oneOrMoreLocales/1DBlockDistributedJacobi.chpl:  proc initialize() {
- [x] test/types/type_variables/deitz/part3/test_instantiate_construct1.chpl:  proc initialize() {
- [x] test/types/type_variables/deitz/test_call_with_type_side_effects.chpl:  proc initialize() {
- [x] test/types/type_variables/ferguson/ispod-initialize.chpl:  proc initialize() {
- [x] test/types/typedefs/nelson/typedefFixingParameter.chpl:  proc initialize() { 

Failed testing: (issue with enum array field)
- [x] test/studies/hpcc/HPL/marybeth/Init.chpl:  proc initialize() {
- [x] test/studies/hpcc/HPL/marybeth/ReadInputFile.chpl:  proc initialize() {

Controversial:
- [ ] test/distributions/diten/blockCyclicDist.chpl:  proc initialize() {
- [ ] test/distributions/diten/blockCyclicDist.chpl:  proc initialize() {
- [ ] test/distributions/diten/blockCyclicDist.chpl:  proc initialize() {

Tests of the functionality itself (to remove when completely deprecated):
- [ ] test/classes/bradc/initialize-primary.chpl:  proc initialize() {
- [ ] test/classes/bradc/initialize-secondary.chpl:proc C.initialize() {
- [ ] test/classes/diten/record_initialize.chpl:  proc initialize() {
- [ ] test/classes/diten/record_initialize.chpl:  proc initialize() {
- [ ] test/classes/initializers/compilerGenerated/initializeMethod.chpl:  proc initialize() {
- [ ] test/classes/marybeth/test-class-init.chpl:  proc initialize() {
- [ ] test/trivial/diten/class_domain_init.chpl:  proc initialize(){

**Comment by bradcray** [comment]
Last night I was reading in the initializers documentation:  "In release 1.17.0, defining an overload of the postinit method is sufficient to suppress the default record constructors. This implies that it is not possible to initialize instances of this type without including one or more user-defined init methods."  

This makes me think that we won't be able to convert `initialize()` methods over to `postinit()` for cases that wanted to lean on compiler-provided initializers until this is improved/fixed (i.e., I don't think we should manually insert a user initializer that reproduces what the compiler-provided inializer would do?).  I was also wondering whether the compiler could use the presence of `postinit()` as a cue that it should generate a default initializer until such time as all records/classes get default initializers?

**Comment by lydia-duncan** [comment]
So far these updates haven't seemed to cause problems, but I might have just been lucky.

**Comment by bradcray** [comment]
Does that mean they have defined `init()` routines?

**Comment by lydia-duncan** [comment]
I haven't had to explicitly add any and it does look an `init()` method is generated for the type.

**Comment by lydia-duncan** [comment]
So far I've mostly touched classes, though

**Comment by bradcray** [comment]
Does that imply that the documentation is wrong?

**Comment by lydia-duncan** [comment]
Yeah, I think so.  I didn't pay as much attention to that section when reviewing it, since I hadn't worked on it and so didn't feel as confident in my knowledge of the status.  I'll throw together an update on that

**Comment by lydia-duncan** [comment]
Most everything was convertible, aside from a few tests that were testing the initialize() method itself.

There were just three exceptions: one execution segfault, one incorrect behavior, and one test that had relied upon altering a const field during the initialize method.  I'm going to coordinate with Ben H on these.

**Comment by mppf** [comment]
Can this epic be closed now?

**Comment by lydia-duncan** [comment]
I think so.  @benharsh - do you know of any outstanding initialize() methods?

**Comment by benharsh** [comment]
Nope, they're all gone. I'll close the issue.
