### ISSUE TITLE
delete-free subtask: convert all modules/tests to use raw or owned

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#9087]
As a Chapel implementer, I need the modules and tests to pass as progress continues on the delete-free implementation. To enable that progress, I need the modules and tests to use raw, shared, or owned pointers so that the lifetime checker can work correctly. Additionally, the effort to convert existing code over to the new delete-free story will enable us to discover bugs and design issues.

Acceptance Criteria:
A version of the compiler that raises an error on a class 'new' that is not decorated with raw / shared / owned passes testing.

**Comment by mppf** [comment]
I have a Hello World test working with this.

**Comment by mppf** [comment]
As of today, I have test/release/examples/primers passing here with --warn-unstable (and it set to warn on un-decorated new calls). There are approximately 300 failures in full testing with that code (mainly stemming from incomplete changes to distributions).

**Comment by mppf** [comment]
See also test/arrays/deitz/test_block_array_of_ints_assigned_class_field.chpl which fails if it uses owned... but that has to do with forall intents.

Recent test run gives [Summary: #Successes = 6641 | #Failures = 2103 | #Futures = 0] - more tests are failing due to improved error reporting.

**Comment by mppf** [comment]
test/arrays/deitz/part5/test_promote_constructor.chpl fails if it uses unmanaged, but that seems to be fixed by using an initializer (vs constructor), but this test doesn't pass if using an initializer.

**Comment by mppf** [comment]
If it becomes necessary from experience with this issue, reopen  #9537.

**Comment by mppf** [comment]
Currently there are 1331 failing tests with --warn-unstable.

**Comment by mppf** [comment]
Currently 785 failures with --warn-unstable

**Comment by mppf** [comment]
- [ ] classes/initializers/phase1/domainMaps/init-dmap-dom-arr-local -- dmap type constructor should inhibit error

**Comment by mppf** [comment]
- [ ] TOML and MasonUpdate / mason tests

**Comment by mppf** [comment]
- [ ] test/functions/ferguson/query/query-generic-type-leaf-q.chpl with borrowed decorator

**Comment by mppf** [comment]
- [ ] exercises/boundedBuffer/solutions/boundedBuffer-atomic

**Comment by mppf** [comment]
- [ ] parallel/taskPar/taskIntents/ri-coforall+on

**Comment by mppf** [comment]
- [ ] multilocale/deitz/linked/test_linked2 using owned

**Comment by mppf** [comment]
- [ ] parallel/taskPar/taskIntents/ri-coforall+on and other reductions tests

**Comment by mppf** [comment]
--warn-unstable fails due to enums error:
arrays/bradc/enumarray2.chpl
arrays/bradc/enumIterate.chpl
arrays/diten/enumArrayMethods.chpl
arrays/ferguson/enumerated-array.chpl
arrays/ferguson/enumerated-array2.chpl
associative/diten/enumArrays.chpl
classes/bradc/arrayInClass/arrayOfArithInClass.chpl
classes/bradc/arrayInClass/genericArrayInClass-arith.chpl
classes/bradc/arrayInClass/genericArrayInClass-otharrs.chpl
classes/bradc/arrayInClass/genericArrayInClass-real.chpl
classes/bradc/arrayInClass/genericClassArray-named.chpl

**Comment by mppf** [comment]
- [ ] classes/forwarding/forwarding-generic-default with unmanaged

**Comment by mppf** [comment]
Also includes certain release/examples tests flagged in earlier work (PR #9499) (prefer using `owned` in these rather than `unmanaged` or `borrowed`): (there are 10 of these):
* ~~~test/release/examples/benchmarks/hpcc/stream-ep.chpl~~~
* test/release/examples/benchmarks/shootout/chameneosredux.chpl
* test/release/examples/benchmarks/ssca2/SSCA2_Modules/SSCA2_driver.chpl
* test/release/examples/benchmarks/ssca2/SSCA2_Modules/SSCA2_kernels.chpl  
* test/release/examples/benchmarks/ssca2/SSCA2_Modules/analyze_RMAT_graph_associative_array.chpl
* test/release/examples/benchmarks/ssca2/SSCA2_Modules/analyze_torus_graphs_stencil_rep_v1.chpl             
* test/release/examples/benchmarks/ssca2/SSCA2_Modules/torus_graph_generator_utilities.chpl                 
* ~~~test/release/examples/primers/learnChapelInYMinutes.chpl~~~
* test/release/examples/programs/linkedList.chpl
* test/release/examples/programs/tree.chpl

**Comment by mppf** [comment]
- [ ] release/examples/users-guide/taskpar/walkTreeUsingBegins.chpl

**Comment by mppf** [comment]
- [ ] release/examples/programs/genericStack.chpl
- [ ] release/examples/programs/tree.chpl

**Comment by mppf** [comment]
- [ ] release/examples/primers/locales.chpl

**Comment by mppf** [comment]
Currently on commit f9ecb426dd21f604d488ead14467c90b7e7754e9:
```
[Error matching program output for arrays/bradc/enumIterate]
[Error matching program output for arrays/bradc/enumarray2]
[Error matching program output for arrays/diten/enumArrayMethods]
[Error matching program output for arrays/ferguson/enumerated-array (compopts: 1)]
[Error matching program output for arrays/ferguson/enumerated-array (compopts: 2)]
[Error matching program output for arrays/ferguson/enumerated-array2 (compopts: 1)]
[Error matching program output for arrays/ferguson/enumerated-array2 (compopts: 2)]
[Error matching program output for associative/diten/enumArrays]
[Error matching program output for classes/bradc/arrayInClass/arrayOfArithInClass]
[Error matching program output for classes/bradc/arrayInClass/genericArrayInClass-arith]
[Error matching program output for classes/bradc/arrayInClass/genericArrayInClass-otharrs]
[Error matching program output for classes/bradc/arrayInClass/genericArrayInClass-real]
[Error matching program output for classes/bradc/arrayInClass/genericClassArray-named]
[Error matching compiler output for distributions/bradc/wrongDomForDist/wrongType3]
[Error matching program output for domains/deitz/test_enum_domain1]
[Error matching program output for domains/methods/shape]
[Error matching program output for domains/vass/assoc-domain-assign-1]
[Error matching compiler output for domains/vass/assoc-idxtype-error-1]
[Error matching program output for domains/vass/enumerated-domain-initializer-1]
[Error matching program output for release/examples/benchmarks/lcals/LCALSMain]
[Error matching program output for release/examples/benchmarks/miniMD/miniMD (compopts: 1)]
[Error matching program output for release/examples/benchmarks/miniMD/miniMD (compopts: 2)]
[Error matching program output for release/examples/spec/Classes/classDeinitializer]
[Error matching program output for release/examples/spec/Classes/declaration]
[Error matching program output for release/examples/spec/Classes/delete]
[Error matching program output for release/examples/spec/Classes/getterSetter]
[Error matching program output for release/examples/spec/Classes/simpleConstructors]
[Error matching program output for release/examples/spec/Domains/clearAssociativeDomain]
[Error matching program output for release/examples/spec/Generics/NodeClass]
[Error matching program output for release/examples/spec/Generics/constructorsForGenericFields]
[Error matching program output for release/examples/spec/Generics/fieldWithoutType]
[Error matching program output for release/examples/spec/Generics/genericStack]
[Error matching program output for release/examples/spec/Iterators/recursive]
[Error matching program output for release/examples/spec/Methods/implicitThis]
[Error matching program output for release/examples/spec/Methods/thisMethod]
[Error matching program output for release/examples/spec/Records/recordDeinitializer]
[Error matching program output for release/examples/spec/Statements/defer1]
[Error matching program output for release/examples/spec/Statements/defer2]
[Error matching program output for release/examples/spec/Statements/defer3]
[Error matching program output for release/examples/spec/Task_Parallelism_and_Synchronization/beginWithSyncVar]
[Error matching program output for studies/bale/toposort/toposort (execopts: 1)]
[Error matching program output for studies/bale/toposort/toposort (execopts: 2)]
[Error matching program output for types/enum/diten/enumDom]
[Summary: #Successes = 9084 | #Failures = 43 | #Futures = 0]
```

That's:
 * enum failures (expected)
 * spec tests (future work - #10631)
 * toposort (which I'll email Ian about)

I think that's enough to close this epic. Yay!
