### ISSUE TITLE
Convert my internal list of TODOs into issues

### ISSUE THREAD

**Issue by ronawho** [chapel-lang/chapel#9368]
Here's some TODOs that I've been putting converting into issues. Hopefully opening this issue will be a forcing function to actually get around to that.

Here's most of them:

---
Misc: 
 - [ ] create a simple "no-op" launcher (a hook so we can set env vars)
 - [x] remove block report support (#10127)
 - [ ] operator overloads for atomic ops
 - [ ] stabilize order of  argument bundles
 - [x] possible ra scalability regression (https://github.com/chapel-lang/chapel/issues/9435)
 - [x] verify how much memory is being used for task stacks
 - [x] improve genGraphs speed (#9430)

---
Third-party:
 - [ ] gasnet collab meta-issue
 - [ ] upgrade to jemalloc 5
 - [ ] upgrade to hwloc 2
 - [ ] qthread arm assembly
 - [ ] qthread hwloc 2
 - [ ] qthread faster syncs
 - [ ] fix build with tasks=qthreads hwloc=none

---
Performance:
 - [x] make llvm the default (#9902)
 - [ ] add test for sync vs atomic mutex performance
 - [x] add a mutex/lock library (#9881)
 - [x] make sync barrier reusable (#9734)
 - [x] avoid serialization of sync vars (#9651, #9737)
 - [ ] user-selectable between-locale barrier
 - [ ] corespec
 - [x] avoid dynamic array registration for serial init (#9616)
 - [x] bulk/vector spawn (#9613/#9614)
 - [x] qthreads+OpenMP interference (#9882)
 - [ ] better local barrier implementations
 - [ ] comm/compute overlap?
 - [x] task resetting  (#9618)
 - [ ] LICM improvements
 - [ ] can't inline zippered multi-dimensional iterators
 - [ ] 2D promoted operation performs poorly

---
Benchmark Elegance:
 - [ ] remove difference between ISx release and hand-optimized
 - [ ] reduce diff between elegant and opt (requires task private vars)

---
Benchmarks Perf Optimizations:
 - [x] update ml compopts/execopts to use "scalable numbers" (#9626)
 - [x] LCALS: (#9623)
   - [x] task spawning speed (#9614)
 - [x] Stream: (#9617)
   - [x] arrays on hugepages hurts perf (#7852)
   - [x] scalability for global (#9613)
 - [x] RA: (#9625)
   - [x] add oversub variants (included in RA epic)
 - [x] PRK-stencil: (#9620)
   - [x] task resetting (#9618)
   - [x] scalability (#9613)
 - [x] ISX: (#9622)
   - [x] FMA vs RDMA (bte) (#9615)
   - [x] allocate arrays out of dynamic heap (#9616)

**Comment by ronawho** [comment]
I've converted all the benchmark optimizations/improvements into issues. It took a pretty long time to capture most of that information, so I'm going to call that good enough for now. I've removed this from the current sprint (and made https://github.com/chapel-lang/chapel/issues/9627 just to fill for the sprint planning)

**Comment by ronawho** [comment]
Closing, I think most of these have been captured in other issues, or are no longer relevant.
