### ISSUE TITLE
spike: is lower-overhead error handling possible?

### ISSUE THREAD

**Issue by psahabu** [chapel-lang/chapel#9380]
## user story
As a Chapel programmer, I want error handling to be near zero-cost, because while I like handling errors without halting, I also want my programs to be performant.

### tasks
- [ ] investigate the design space
- [ ] decide if this is a worthwhile effort
- [ ] if so, what strategy should be pursued?

### motivation
Today, there is a conditional for every throwing call, even if no error is raised. Here's a high level example of lowered error handling:

```chapel
proc throwingCall(out error: Error) {
  error = someError;
}

var err: Error;
throwingCall(err);
if err then
  goto handleErrorHere;

handleErrorHere:
if err then
   // handle the error
```

### pass goto to throwing calls
It may be possible to pass a 'goto arg' (called `GotoPoint` below) from the calling function to the throwing function. This would allow the throwing function to jump directly to the calling function's error handling segment. This eliminates the conditional on each throwing call, but would leave a single conditional for each try.

```chapel
proc throwingCall(out error: Error, handleErrorHere: GotoPoint) {
  error = someError;
  goto handleErrorHere;
}

var err: Error;
throwingCall(err, handleErrorHere);

handleErrorHere:
if err then
   // handle the error
```
### goto guard of error handling segment
Another `goto` could be used to skip the `try` conditional, in combination with the previous proposal:

```chapel
var err: Error;
throwingCall(err, handleErrorHere);
goto noError;  // continued past throwing call, handleErrorHere can be skipped

handleErrorHere:
if err {
   // handle the error
}
noError:
// continues
```
