### ISSUE TITLE
Misc memory tracking improvements

### ISSUE THREAD

**Issue by ronawho** [chapel-lang/chapel#9509]
Just a grab bag of improvements for memory tracking.

- [x] Fix memory tracking for ugni (https://github.com/chapel-lang/chapel/issues/9497)
      - add a test to `test/runtime/configMatters/comm` to make sure we don't break this again
- [x] Speed up memory tracking (currently uses a sync as a lock, maybe use atomic spin-wait lock)
- [x] Start some nightly multi-locale memLeak testing (probably limited to release/examples for now)
     - will likely require some changes to `util/devel/analyzeMemLeaksLog`

We could also consider adding a lighter-weight mechanism. `--memTrack` is pretty heavyweight -- it basically tracks every allocation/deallocation in a lock-protected hash-table. Maybe we could use atomic counters like we do for comm diags and things like that to provide a much faster "were there any leaks" check?

**Comment by e-kayrakli** [comment]
> will likely require some changes to util/devel/analyzeMemLeaksLog

I have run some basic tests, and this depends on what we want memleaks testing to report. Currently, if this script is run on a memleaks log file, it sums up leaks from all locales.

1. I like this, because, logically you leak all that memory in your run and it should be reported.
2. I don't like this, because, one may look at the bytes leaked and get scared by the amount. Although the leaks across locales are most generally the same stuff repeating.

Personally, I don't see the concern in (2) to be important. Moreover, I can't see any good alternatives to this behavior (averaging, reporting only one locale etc).

**Comment by e-kayrakli** [comment]
> probably limited to release/examples for now

From the time this issue was opened until now I think we made enough progress that closing `release/examples` memleaks for multilocale tests doesn't seem too difficult (#14510). Whether that PR gets in or not, I think we should just run the full test suite.

**Comment by ronawho** [comment]
@e-kayrakli added multi-locale memory leak testing (that runs all multi-locale tests). The graphs are up [here](https://chapel-lang.org/perf/chapcs/?startdate=2019/12/05&enddate=2020/01/23&graphs=memoryusageformultilocaletests,memoryleaksformultilocaletests,numberofmultilocaletestswithleaks)
