### ISSUE TITLE
Spike: Explore disabling casts on enums

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#9821]
As a user, I'd prefer my enums that have no integer values associated with them to not support casting to integers in order to avoid assumptions that they are 0- or 1-based by default, and to provide a nice abstract concept of an enum.

Acceptance criteria:
* we make a decision as to whether or not to support this feature
* we understand the implications of supporting it
* we have tasks identified to add support for it

**Comment by bradcray** [comment]
There has been support for, and no opposition to, this proposal, and I was able to implement the core of the change in fairly short order.  However, I wasn't able to resolve all issues in order to merge it in this sprint, so have created follow-on issues to capture things that need to be addressed prior to merging and a new epic #10026 to track these related issues:

- [ ] issue #10025 is the most concerning one, as it breaks cases where scoped enums want to print themselves out, and it seems like it will be tricky to fix (involves function resolution)
- [ ] issue #10027 involves resolving a few cases that I broke by changing how enums are stored in binary files
- [ ] issue #10028 involves restoring some compile-time errors that I disabled
- [ ] issue #10030 involves some miscellaneous cases that I wasn't yet able to describe any better, yet which seem like they might be fairly easy

I also added issue #10029 which, though not strictly required for this epic, would arguably bring our enum support more in-line with other types.
