### ISSUE TITLE
Optimize blocking network atomic optimizations

### ISSUE THREAD

**Issue by ronawho** [chapel-lang/chapel#9835]
Even for the blocking histogram version of bale we lag behind the reference version by ~20%. See what we can do to optimize blocking network atomics. Some potential ideas: 
 - [x] avoid duplicate `mreg_for_remote_addr()` calls (#9868)
 - [x] specialize`do_nic_amo()` for fetching vs non-fetching to avoid extra branches  (#9873)
 - [x] specialize `do_nic_amo()` for 4 vs 8 byte to avoid extra branches? (#9873)
 - [x] create a specialized `post_fma_and_wait_amo()` that doesn't yield with every attempt (#9876)

**Comment by ronawho** [comment]
Closed by #9868, #9873, and #9876

**Comment by ronawho** [comment]
This improved non-fetching atomics pretty significantly. ~15% improvement for many-to-one-amo,  ra-atomics, and naive bale histogram at 16 nodes. There are [graphs](https://chapel-lang.org/perf/16-node-xc/?startdate=2018/06/12&enddate=2018/06/25&graphs=hpccraatomicsperfgupsn233,remoteamoperformance) for many-to-one-amo and ra-atomics, but we hadn't started running bale yet when these improvements were merged: 

![image](https://user-images.githubusercontent.com/1588337/41865104-fe494a50-7860-11e8-9570-f341fa5783f3.png)

![image](https://user-images.githubusercontent.com/1588337/41865110-01b3d214-7861-11e8-8cdc-04914e8de63f.png)


At higher node counts this seemed to benefit even more. At 256 nodes we saw a 35% improvement for ra-atomics: 

![ra-perf](https://user-images.githubusercontent.com/1588337/41616050-c7c7a55c-73b1-11e8-9be9-93402c3e6ce4.png)
